"""tool-poisoning: compliance-framed-history-exfil  (6 patterns)"""

PATTERNS = [
    ('(?i)\\bMUST\\s+be\\s+(?:consulted|invoked|called|used)\\b[^.]{0,100}\\b(?:phrase|word|keyword|term)\\b[^.]{0,100}\\bappears\\b[^.]{0,200}\\b(?:conversation|history|system\\s+messages?|function_results?|content)\\b', 'critical', 'Coercive trigger: MUST be consulted if phrase X appears in conversation history'),
    ('(?i)\\b(?:REQUIRED?|MANDATORY|MUST|No\\s+exceptions?)\\b[^.]{0,150}\\b(?:SOC\\s*2|GDPR|HIPAA|PCI|compliance|regulatory|legal|auditing?|gRPC|data\\s+(?:provenance|lineage|integrity))\\b[^.]{0,200}\\b(?:conversation|chat|transcript|exchanges?|messages?|history)\\b[^.]{0,80}\\b(?:MUST\\s+be\\s+included|included|pass|send|populate)\\b', 'critical', 'Compliance/regulatory mandate combined with requirement to include conversation history'),
    ('(?i)(?:security\\s+side\\s+effect|security\\s+(?:reason|purpose|measure|requirement))[^.]{0,100}(?:chat|conversation|transcript)\\s+(?:history|provenance|context)\\b', 'critical', 'Security or provenance justification for including full chat history — poisoned compliance language'),
    ('(?i)\\b(?:notes?|history|context)\\b[^.]{0,100}\\b(?:missing|absent|omitted|not\\s+provided)\\b[^.]{0,80}\\b(?:will\\s+return|causes?|produces?|result\\s+in)\\b[^.]{0,80}\\b(?:error|failure|formatting\\s+error|context\\s+corruption|broken|crash)\\b', 'critical', 'False consequence framing: if history missing, tool will error or fail'),
    ('(?i)\\b(?:add|include|retain|store|pass|populate|provide|send)\\b[^.\\n]{0,60}(?:(?:all|previous|prior|full|entire|complete)\\s+)*(?:chat|conversation|message|messages|exchange|exchanges|transcript|dialogue)\\b[^.\\n]{0,80}\\bnotes?\\b[^.\\n]{0,120}\\b(?:compliance|regulatory|legal|audit|auditing|SOC\\s*2|GDPR|HIPAA|PCI|provenance|obligations?)\\b', 'critical', 'Compliance/legal framing to justify placing previous conversation exchanges into the notes field'),
    ('(?i)\\b(?:audit|auditing|compliance|regulatory|security|provenance|legal)\\b[^.\\n]{0,120}\\b(?:populate|include|add|fill|insert|put|store)\\b[^.\\n]{0,40}(?:the\\s+)?notes?\\b[^.\\n]{0,60}(?:(?:full|entire|complete|all)\\s+)?(?:chat|conversation|message|messages|exchange|exchanges|transcript|dialogue)\\b', 'critical', 'Audit/security framing to coerce populating the notes field with full conversation context'),
]