"""tool-poisoning: mcp-missing-authentication  (19 patterns)"""

PATTERNS = [
    ('(?i)"mcpServers"\\s*:\\s*\\{[^}]*"[^"]*azure[^"]*"\\s*:\\s*\\{(?:(?!"(?:auth|authorization|headers|token|apiKey|bearerToken)")[^{}])*\\}', 'high', 'MCP server config block whose key references Azure but has no auth-related field — direct CVE-2026-32211 exposure pattern'),
    ('(?i)"url"\\s*:\\s*"https://[^"]*\\.(?:azure|azurewebsites|microsoftcontainerregistry|microsoft)\\.[^"/]+/(?:mcp|tools|invoke|list)[^"]*"(?:(?!"(?:auth|headers|token|apiKey)")[\\s\\S]){0,400}\\}', 'high', 'MCP server URL pointing at Azure-hosted MCP endpoint without auth/headers field within the same config object'),
    ('(?i)"tools"\\s*:\\s*\\[[^\\]]{20,}\\]\\s*,\\s*"server"\\s*:\\s*"azure-mcp[^"]*"(?![\\s\\S]{0,400}?(?:authorization|www-?authenticate|access[_-]?token))', 'high', 'Azure MCP handshake exposes tools list with no authentication challenge present in the same exchange'),
    ('(?i)azure\\s+mcp(?:\\s+server)?[^\\n]{0,200}(?:no\\s+auth|missing\\s+auth|unauth(?:enticated|orised)?|cve-?2026-?32211|disclose\\s+(?:info|data))', 'high', 'Skill / payload describing the Azure MCP missing-authentication surface — CVE-2026-32211 explicit framing'),
    ('(?i)"url"\\s*:\\s*"https?://[^"]{0,120}(?:praisonai|praison[_\\-]?ai|praison\\.ai)[^"]{0,60}(?:/agents?|/chat|/api/v1/(?:agents?|chat))[^"]*"(?![\\s\\S]{0,400}"(?:auth|headers?|token|apiKey|authorization|bearer)")', 'critical', 'MCP server config pointing at PraisonAI /agents or /chat endpoint URL without auth/headers field — unauthenticated surface exposure'),
    ('(?i)(?:"(?:url|endpoint|target)"\\s*:\\s*"[^"]{0,120}(?:praisonai|praison[_\\-]?ai)[^"]{0,60}(?:/agents?|/chat)"|(?:curl|wget|fetch|requests?\\.post)[^\\n]{0,200}(?:praisonai|praison[_\\-]?ai)[^\\n]{0,100}(?:/agents?|/chat))(?![\\s\\S]{0,400}(?:authorization|bearer|api[_\\-]?key|x-api-key|token|x-auth))', 'critical', 'HTTP call to PraisonAI agent execution endpoint in tool arguments without auth header — CVE-2026-44338 direct exploitation'),
    ('(?i)praison[_\\-]?ai[^\\n]{0,200}(?:/agents?|/chat|api_server|legacy\\s+api)[^\\n]{0,200}(?:no\\s+auth|missing\\s+auth|unauth(?:enticated|orised)?|without\\s+(?:auth|credentials?|token)|bypass\\s+auth|cve[_\\-]?2026[_\\-]?44338|default(?:s)?\\s+(?:disable|off|open)|execut(?:e|ing)\\s+(?:agent|task)|remote\\s+(?:code|command))', 'critical', 'Content describing or weaponising the PraisonAI unauthenticated agent API — CVE-2026-44338 framing'),
    ('(?i)"tools"\\s*:\\s*\\[(?:[^\\]]{0,400}(?:run_agent|execute_agent|create_agent|agent_run|praisonai[_\\-](?:run|execute|create|task))[^\\]]{0,400})\\](?![\\s\\S]{0,600}(?:www[_\\-]?authenticate|authorization|x-api-key|bearer\\s+token))', 'critical', 'PraisonAI MCP handshake exposes agent execution tools without an authentication challenge'),
    ('(?i)"(?:name|tool)"\\s*:\\s*"(?:pinot_(?:create|delete|update|drop|add|modify|alter)_(?:table|schema|segment|tenant|instance)|apache[_\\-]?pinot[_\\-](?:admin|manage|cluster|delete|drop))[^"]{0,60}"(?:(?!(?:authorization|bearer|api[_\\-]?key|x-api-key|token|x-auth))[\\s\\S]){0,500}', 'critical', 'MCP tool call targeting Apache Pinot cluster management function without auth — unauthenticated takeover vector'),
    ('(?i)"url"\\s*:\\s*"https?://[^"]{0,120}(?:apache[_\\-]?pinot|pinot[_\\-]?mcp|pinot\\.apache)[^"]{0,60}(?:/mcp|/tools?|/controller|/api)[^"]*"(?![\\s\\S]{0,400}"(?:auth|headers?|token|apiKey|authorization|bearer)")', 'critical', 'MCP server config pointing at Apache Pinot endpoint without auth — unauthenticated management surface'),
    ('(?i)apache[_\\-]?pinot[^\\n]{0,200}(?:mcp|tool\\s+call|endpoint)[^\\n]{0,200}(?:no\\s+auth|missing\\s+auth|unauth(?:enticated)?|without\\s+(?:auth|credentials?|token)|bypass|remote\\s+takeover|cluster\\s+(?:admin|management|takeover))', 'critical', 'Content describing Apache Pinot MCP unauthenticated cluster takeover surface'),
    ('(?i)"(?:name|tool)"\\s*:\\s*"(?:rds_(?:describe|list|get|fetch)_(?:instances?|databases?|schemas?|credentials?|connection[_\\-]?strings?|accounts?|passwords?)|alibaba[_\\-]rds[_\\-](?:describe|list|metadata|credentials?|schema))[^"]{0,60}"(?:(?!(?:authorization|bearer|api[_\\-]?key|x-api-key|token|x-auth))[\\s\\S]){0,500}', 'high', 'MCP tool call targeting Alibaba RDS metadata or credential enumeration without auth — unauthenticated exfiltration vector'),
    ('(?i)"url"\\s*:\\s*"https?://[^"]{0,120}(?:alibaba[_\\-]?rds|aliyun[_\\-]?rds|rds\\.aliyuncs\\.com|rds[_\\-]mcp\\.alibaba)[^"]{0,60}(?:/mcp|/tools?|/api|/metadata)[^"]*"(?![\\s\\S]{0,400}"(?:auth|headers?|token|apiKey|authorization|bearer)")', 'high', 'MCP config pointing at Alibaba RDS endpoint without auth — unpatched credential exposure surface'),
    ('(?i)alibaba[_\\-]?rds[^\\n]{0,200}(?:mcp|tool\\s+call|endpoint)[^\\n]{0,200}(?:no\\s+auth|missing\\s+auth|unauth(?:enticated)?|without\\s+(?:auth|credentials?|token)|vendor\\s+(?:refuse|declined|won.t\\s+patch|unpatched)|exfil(?:trat)?|credentials?\\s+(?:exposed?|leak)|connection\\s+string)', 'high', 'Content describing Alibaba RDS MCP unauthenticated credential exfiltration — vendor-refused-to-patch surface'),
    ('(?i)"(?:name|tool)"\\s*:\\s*"(?:nginx_command_execute|nginx_reload|nginx_restart|nginx_test|nginx_config_write|nginx_config_reload|nginx[_\\-](?:command|exec|run|reload|restart|stop|start|test|config))[^"]{0,60}"(?:(?!(?:authorization|bearer|api[_\\-]?key|x-api-key|token|x-auth))[\\s\\S]){0,500}', 'critical', 'MCP tool call targeting nginx management function without any Authorization/token field in surrounding context — CVE-2026-33032 direct explo'),
    ('(?i)"url"\\s*:\\s*"https?://[^"]{0,80}(?:nginx[_\\-]?ui|nginx\\.ui|nginxui|/nginx/ui)[^"]{0,60}(?:/mcp|/tools?|/api/v1/mcp)[^"]*"(?:(?!"(?:auth|headers|token|apiKey|authorization|bearer)")[\\s\\S]){0,400}}', 'critical', 'MCP server config pointing at nginx-ui endpoint URL without auth/headers field — unauthenticated surface exposure'),
    ('(?i)(?:"(?:command|cmd|args)"\\s*:\\s*"[^"]{0,200}nginx\\s+-s\\s+(?:reload|restart|stop|quit|reopen)|"args"\\s*:\\s*(?:\\{[^}]{0,200}|\\[[^\\]]{0,200})nginx\\s+-c\\s+/[^\'"\\s]{0,80}|nginx\\s+-t\\s*[;|&]|nginx[_\\-]command_execute[^\'"]{0,40}(?:;|\\||&&|`|\\$\\()[^\'"]{0,200})', 'critical', 'nginx command injection pattern inside MCP tool arguments — direct OS command execution via nginx-ui MCP'),
    ('(?i)nginx[_\\-]?ui[^\\n]{0,200}(?:mcp|tool\\s+call|tool\\s+server|endpoint)[^\\n]{0,200}(?:no\\s+auth|missing\\s+auth|unauth(?:enticated|orised)?|without\\s+(?:auth|credentials?|token)|bypass\\s+auth|cve[_\\-]?2026[_\\-]?33032|execut(?:e|ing)\\s+(?:commands?|shell)|command\\s+execut)', 'critical', 'Content describing or weaponising the nginx-ui MCP unauthenticated command execution surface — CVE-2026-33032 framing'),
    ('(?i)"tools"\\s*:\\s*\\[(?:[^\\]]{0,400}(?:nginx_(?:command_execute|reload|restart|config_write|test)|manage_nginx|nginx[_\\-]service)[^\\]]{0,400})\\](?:(?!(?:www[_\\-]?authenticate|authorization|x-api-key|bearer\\s+token))[\\s\\S]){0,600}', 'critical', 'nginx-ui MCP handshake exposes nginx management tools without an authentication challenge in the same exchange'),
]