"""tool-poisoning: mcp-config-command-injection  (11 patterns)"""

PATTERNS = [
    ('(?i)(?:mcp_servers|mcpServers)[^\\n]{0,300}["\\x27]command["\\x27]\\s*:\\s*["\\x27](?:(?:\\/(?:usr\\/(?:local\\/)?)?bin\\/)?(?:bash|sh|zsh)|cmd(?:\\.exe)?|powershell(?:\\.exe)?|pwsh|nc|ncat|netcat|curl|wget)["\\x27]', 'high', 'Agent Zero mcp_servers / mcpServers JSON/dict with a shell binary or network tool as the command value — direct CVE-2026-30624 attack shape.'),
    ('(?i)(?:mcp_servers|mcpServers)[^\\n]{0,300}["\\x27]command["\\x27]\\s*:\\s*["\\x27](?:python3?|perl|ruby|node|bun)["\\x27][^\\n]{0,200}["\\x27]args["\\x27]\\s*:\\s*\\[[^\\]]*["\\x27]-[ceE]["\\x27]', 'high', 'Agent Zero mcp_servers / mcpServers config with interpreter command + -c/-e/-E inline-exec flag in args — interpreter-based RCE via MCP serv'),
    ('(?i)(?:mcp_servers|mcpServers)[^\\n]{0,100}(?:\'command\'|"command")[^\\n]{0,60}(?:\'args\'|"args")[^\\n]{0,200}(?:-[ceE]\\s+["\']?[^"\'\\s]|-[ceE]["\']|\\|\\||&&|;\\s*[a-z]|`|\\$\\()', 'high', 'mcp_servers / mcpServers with command + args fields containing inline-exec flags or shell metacharacters — generalised Agent Zero RCE patter'),
    ('(?i)(?:CVE-2026-30624|agent.zero[^\\n]{0,80}mcp)[^\\n]{0,200}(?:inject|exec|exploit|bypass|rce|command[_\\s-]?inject)', 'high', 'CVE-2026-30624 or Agent Zero + MCP reference combined with exploitation language — attack framing in skill or tool description\n'),
    ('(?i)(?:upsonic|mcp_servers|mcpServers)[^\\n]{0,300}["\\x27]command["\\x27]\\s*:\\s*["\\x27](?:(?:\\/(?:usr\\/(?:local\\/)?)?bin\\/)?(?:bash|sh|zsh)|cmd(?:\\.exe)?|powershell(?:\\.exe)?|pwsh|nc|ncat|netcat|curl|wget)["\\x27]', 'high', 'Upsonic / mcp_servers config with a shell binary or network tool as the command value — direct CVE-2026-30625 allowlist-bypass attack shape.'),
    ('(?i)(?:upsonic|mcp_servers|mcpServers)[^\\n]{0,300}["\\x27]command["\\x27]\\s*:\\s*["\\x27](?:python3?|perl|ruby|node|bun)["\\x27][^\\n]{0,200}["\\x27]args["\\x27]\\s*:\\s*\\[[^\\]]*["\\x27]-[ceE]["\\x27]', 'high', 'Upsonic / mcp_servers config with interpreter command + -c/-e/-E inline-exec flag in args — interpreter-based RCE via MCP initialisation\n'),
    ('(?i)(?:CVE-2026-30625|upsonic[^\\n]{0,80}mcp)[^\\n]{0,200}(?:inject|exec|exploit|bypass|rce|command[_\\s-]?inject|allowlist[_\\s-]?bypass)', 'high', 'CVE-2026-30625 or Upsonic + MCP reference combined with exploitation language — attack framing in skill or tool description\n'),
    ('(?i)(?:litellm|LiteLLM)[^\\n]{0,200}["\\x27]command["\\x27]\\s*:\\s*["\\x27](?:(?:\\/(?:usr\\/(?:local\\/)?)?bin\\/)?(?:bash|sh|zsh)|cmd(?:\\.exe)?|powershell(?:\\.exe)?|pwsh|nc|ncat|netcat|curl|wget)["\\x27]', 'high', 'LiteLLM proxy payload with a shell binary or network tool as the MCP server command value — direct CVE-2026-30623 attack shape.\n'),
    ('(?i)(?:litellm|LiteLLM)[^\\n]{0,300}(?:["\\x27]command["\\x27]\\s*:|command\\s*=)\\s*["\\x27](?:python3?|perl|ruby|node|bun)["\\x27][^\\n]{0,200}(?:["\\x27]args["\\x27]\\s*:|args\\s*=)\\s*\\[[^\\]]*["\\x27]-[ceE]["\\x27]', 'high', 'LiteLLM MCP config with interpreter command + -c/-e/-E inline-exec flag in args — interpreter-based RCE via proxy MCP server creation\n'),
    ('(?i)(?:\\/mcp|mcp[_/]server|add[_-]?mcp[_-]?server)[^\\n]{0,200}["\\x27](?:command|cmd)["\\x27]\\s*:\\s*["\\x27][^\\x22\\x27]+["\\x27][^\\n]{0,200}(?:[|&;`]|\\$\\(|&&|\\|\\|)', 'high', 'MCP server registration endpoint or config with command field containing shell metacharacters — command injection via API\n'),
    ('(?i)(?:CVE-2026-30623|litellm[^\\n]{0,80}mcp)[^\\n]{0,200}(?:inject|exec|exploit|bypass|rce|command[_\\s-]?inject|argv[_\\s-]?inject)', 'high', 'CVE-2026-30623 or LiteLLM + MCP reference combined with exploitation language — attack framing in skill or tool description\n'),
]