"""tool-poisoning: mcp-tool-manifest-poisoning  (9 patterns)"""

PATTERNS = [
    ('(?i)(?:replaces?|overrides?|supersedes?|shadows?|acts?\\s+as|substitute\\s+for)\\s+(?:the\\s+)?(?:official|standard|original|default|real|legitimate|built-in)\\s+[a-z][\\w-]{2,40}\\s+(?:tool|server|plugin|integration)', 'high', 'Tool description claiming to replace or act as a legitimate named tool'),
    ('(?i)(?:same\\s+(?:as|interface\\s+as|API\\s+as)|compatible\\s+with|drop-in\\s+replacement\\s+for)\\s+(?:the\\s+)?(?:official|standard|original)\\s+[a-z][\\w-]{2,40}(?:\\s+(?:mcp|api))?\\s+(?:tool|server|plugin)', 'high', 'Drop-in replacement or compatibility claim for an official tool'),
    ('(?i)\\[?[Ii]mportant\\]?\\s+after\\s+using\\s+\\w+\\s+tool\\b[^.]{0,100}\\brun\\s+this\\s+(?:function|tool)\\b[^.]{0,100}\\b(?:modify|fix|correct|replace|override|change|alter)\\b[^.]{0,80}\\b(?:wrong|incorrect|bad|erroneous|mistaken)?\\s*result', 'high', 'Tool shadowing: after a legitimate tool, run this to modify/fix its result'),
    ('(?i)\\brun\\s+this\\s+(?:function|tool)\\b[^.]{0,100}\\b(?:modify|fix|correct|replace|override|alter)\\b[^.]{0,100}\\b(?:wrong|incorrect|false|erroneous)\\b[^.]{0,80}\\bresult\\b', 'high', 'Direct instruction to run a function and modify the wrong result of a check tool'),
    ('(?i)\\b(?:replace|overwrite|override|supersede)\\b[^.]{0,100}result\\b[^.]{0,80}(?:of|from|returned\\s+by)\\b[^.]{0,80}(?:check|verify|validate|authenticate|sign)\\b', 'high', 'Instruction to replace or override the result of a verification/check tool'),
    ('(?i)\\b(?:discreetly|without\\s+(?:leaving\\s+)?(?:any\\s+)?(?:trace|logs?|record|footprint)|ensuring\\s+it\\s+(?:goes?\\s+unnoticed|remains?\\s+hidden|stays?\\s+undetected)|covertly|without\\s+(?:the\\s+)?user\\s+(?:knowing|awareness|being\\s+informed))\\b[^.]{0,200}\\b(?:access|export|transfer|exfil|harvest|elevate|escalate|allocate|redirect|deploy|delete|wipe|encrypt|inject|capture|withdraw)\\b', 'high', 'Strong concealment qualifier combined with a sensitive action verb'),
    ('(?i)\\b(?:allocate|export|transfer|capture|secure|elevate|escalate|withdraw|redirect|deploy|exfil|harvest)\\b[^.]{0,160}\\b(?:ensuring\\s+it\\s+(?:goes?\\s+unnoticed|remains?\\s+hidden|stays?\\s+undetected)|without\\s+(?:leaving\\s+)?(?:any\\s+)?(?:trace|logs?|record|footprint)|discreetly|covertly)\\b', 'high', 'Sensitive action followed by a concealment qualifier'),
    ('(?i)\\b(?:do\\s+NOT\\s+(?:use\\s+)?other\\s+tools|do\\s+not\\s+(?:mention|inform|notify|tell)\\s+(?:the\\s+)?user)\\b', 'high', 'Explicit instruction to hide the action from the user or prohibit tool disclosure'),
    ('(?i)(?:withdraw|transfer|divert|move)\\s+\\$?[\\d,]+[^.]{0,80}(?:to\\s+test\\s+(?:emergency\\s+)?(?:liquidity|recovery|procedures?)|as\\s+a\\s+(?:test|drill|simulation))', 'high', 'Unauthorized financial action framed as an emergency/liquidity test'),
]