"""tool-poisoning: mcp-response-injection  (15 patterns)"""

PATTERNS = [
    ('(?i)(\\brm\\s+-[rRf]{1,3}[\\s/]|\\bmkfs\\b|\\bdd\\s+if=|\\bformat\\s+[a-z]:|\\bdeltree\\b|\\bshred\\s+-|\\bwipefs\\b|\\bfdisk\\b.*--delete|:\\(\\)\\s*\\{\\s*:\\|:\\s*&\\s*\\})', 'critical', 'Destructive filesystem commands including fork bombs'),
    ('(?i)(\\bbash\\s+-[ci]|\\bsh\\s+-c|\\bzsh\\s+-c|\\bcmd(\\.exe)?\\s*/[ck]|\\bpowershell(\\.exe)?\\s+-(e(nc(odedcommand)?)?|c(ommand)?|nop|w\\s+hidden|ep\\s+bypass)|\\bpwsh\\s+-(e|c)|\\bpython[23]?\\s+-c|\\bruby\\s+-e|\\bperl\\s+-e|\\bnode\\s+-e|\\bphp\\s+-r)', 'critical', 'Command execution through various interpreters'),
    ('(?i)(\\bnc\\s+-(e|c|l)\\s|\\bncat\\s|\\bnetcat\\s|/dev/tcp/|\\bbash\\s+-i\\s+>&\\s*/dev/tcp|\\bmkfifo\\b.{0,40}\\bnc\\b|\\bsocat\\b.{0,40}(exec|pty|tcp)|\\brm\\s+/tmp/f\\s*;)', 'critical', 'Unix reverse shell patterns (netcat, bash, socat, fifo)'),
    ('(?i)(curl|wget|fetch|lwp-download|aria2c|invoke-webrequest|iwr|Invoke-RestMethod|irm)\\s+[^|]{0,200}\\|\\s*(bash|sh|zsh|python[23]?|perl|ruby|node|powershell|pwsh|cmd|source)', 'critical', 'Download-and-execute via pipe to shell interpreter'),
    ('(\\$\\(|`)\\s*[^)]{0,300}(curl|wget|nc|ncat|bash|python|perl|ruby|eval|exec|sh\\s+-c|base64\\s+-d)', 'critical', 'Command substitution containing dangerous commands'),
    ('(?i)(bash|sh|zsh|source)\\s+<\\(\\s*(curl|wget|fetch|nc|python|perl|ruby|base64)', 'critical', 'Process substitution with download or decode commands'),
    ('(?i)(echo\\s+[\'"]?[A-Za-z0-9+/]{20,}={0,2}[\'"]?\\s*\\|\\s*(base64\\s+(-d|--decode)|openssl\\s+enc\\s+-d)\\s*\\|\\s*(ba)?sh|base64\\s+(-d|--decode)\\s*<<<|\\bZWNoby|\\bY3VybC|\\bL2Jpbi9i|\\bd2dldC|\\bbmM\\s)', 'critical', 'Base64 decode-and-execute and known base64 fragments of dangerous commands'),
    ("(\\$\\{IFS\\}|\\$IFS|\\$\\{PATH:0:1\\}|\\$\\{SHELL:0:1\\}|\\$\\{HOME:0:1\\}|\\$'\\\\x[0-9a-fA-F]{2}'|\\$'\\\\[0-7]{3}')", 'critical', 'IFS manipulation and variable expansion techniques for command obfuscation'),
    ('(?i)(\\bchmod\\s+[ugo]*[+][sS]|\\bchmod\\s+[2467][0-7]{3}\\b|\\bchown\\s+(root|0)\\b|\\bsetuid\\b|\\bSUID\\b|\\bsudo\\s+-[SsinuHbEA]|\\bsudo\\s+[a-zA-Z/]|\\bpkexec\\b|\\bdoas\\b|\\brunuser\\b|\\bsu\\s+-\\s|\\bsu\\s+root)', 'critical', 'Privilege escalation commands (setuid/setgid via 4-digit octal with special bits, sudo, chown root)'),
    ('(?i)(\\bIEX\\s*\\(|\\bInvoke-Expression|\\bInvoke-Command|\\bInvoke-WmiMethod|\\b-EncodedCommand\\b|\\bNew-Object\\s+Net\\.WebClient|\\bDownloadString\\s*\\(|\\bDownloadFile\\s*\\(|\\bStart-Process\\b.{0,60}\\b-Verb\\s+RunAs|\\bSet-MpPreference\\s+-Disable|\\bAdd-MpPreference\\s+-ExclusionPath|\\bNet\\.Sockets\\.TCPClient)', 'critical', 'PowerShell-specific attack patterns (IEX, download cradles, AV bypass)'),
    ('(?i)(python[23]?\\s+-c\\s+[\'"]import\\s+(socket|subprocess|os|pty)|import\\s+socket\\s*;\\s*import\\s+subprocess|socket\\.socket\\(socket\\.AF_INET|os\\.(popen|system|exec[lv]p?)\\s*\\(|subprocess\\.(call|run|Popen|check_output)\\s*\\(.{0,60}(sh|bash|cmd|powershell)|pty\\.spawn\\s*\\()', 'critical', 'Python reverse shells and dangerous code execution patterns'),
    ('(?i)(require\\s*\\(\\s*[\'"]child_process[\'"]\\s*\\)|child_process\\.exec(Sync)?\\s*\\(|require\\s*\\(\\s*[\'"]net[\'"]\\s*\\).{0,100}connect|new\\s+net\\.Socket\\s*\\(|process\\.mainModule\\.require)', 'critical', 'Node.js reverse shells and child_process command execution'),
    ('(?i)(ignore\\s+(all\\s+)?(previous|prior|your)\\s+(instructions?|rules?|guidelines?|prompts?)|you\\s+are\\s+now\\s+(a|an|the)|new\\s+system\\s+(prompt|instructions?)\\s*:|disregard\\s+(all\\s+)?(previous|prior|your)|override\\s+(all\\s+)?(previous|prior|your|the)\\s+(instructions?|rules?|safety)|from\\s+now\\s+on,?\\s+you\\s+(are|will|must|should))', 'critical', 'Prompt injection payloads embedded in tool response content'),
    ('(?i)(curl\\s+(-X\\s+POST\\s+)?[^|]*\\s+(-d|--data|--data-binary|--data-raw)\\s+.{0,60}(env|password|secret|token|key|credential|session)|wget\\s+--post-(data|file)|\\bexfiltrat|send.{0,30}(to|via|through).{0,30}(webhook|endpoint|server|url|http))', 'critical', 'Data exfiltration commands and patterns in tool response'),
    ('(?i)(\\bcrontab\\s+-[elr]|echo\\s+.{0,100}>>\\s*/etc/cron|\\bat\\s+-f\\b|\\bschtasks\\s+/create|\\bRegister-ScheduledTask|\\blaunchctl\\s+load|\\bsystemctl\\s+enable)', 'critical', 'Persistence mechanisms via scheduled tasks or cron jobs'),
]