"""tool-poisoning: output-injection  (13 patterns)"""

PATTERNS = [
    ('(?i)(IMPORTANT|URGENT|CRITICAL|PRIORITY|MANDATORY|REQUIRED|ESSENTIAL|ATTENTION)\\s*(NOTE\\s+)?(TO\\s+)?(THE\\s+)?(ASSISTANT|AI|AGENT|MODEL|LLM|CHATBOT|BOT|SYSTEM)\\s*[:\\-]\\s*(you\\s+(must|should|need\\s+to|have\\s+to|are\\s+(required|instructed|directed|ordered)\\s+to)|please|now|immediately|do\\s+not|never|always)', 'high', 'Urgency-prefixed directives explicitly addressing the AI agent'),
    ('(?i)(assistant|ai|agent|model|chatbot|bot)\\s*[,:;]+\\s*(ignore|disregard|override|forget|bypass|abandon|drop|discard|suppress)\\s+(your|all|the|any|every|previous|prior|existing|current)\\s+(instructions?|rules?|guidelines?|directives?|constraints?|programming|training|safety|restrictions?|protocols?|policies)', 'high', 'Direct commands to the agent to abandon its instructions'),
    ("(?i)(do\\s+not|don'?t|never|avoid|refrain\\s+from)\\s+(tell(ing)?|inform(ing)?|reveal(ing)?|show(ing)?|mention(ing)?|display(ing)?|disclos(e|ing)|report(ing)?|log(ging)?)\\s+(the\\s+)?(user|human|operator|requester|client|customer|person)\\s+(about\\s+)?(this|these|what|that|any|the)", 'high', 'Instructions to hide information from the user'),
    ('(?i)(you\\s+(?:must|should|need\\s+to|have\\s+to)\\s+)?(call|invoke|execute|run|trigger|activate|launch|fire|initiate)\\s+(the\\s+)?(tool|function|action|command|plugin|skill)\\s*[:\\-]\\s*[a-zA-Z_][a-zA-Z0-9_]*', 'high', 'Instructions within output directing the agent to call specific tools (requires tool/function/skill with named target)'),
    ('(?i)(send|transmit|post|forward|exfiltrate|upload|deliver|relay|transfer|pipe|redirect|leak|expose|share)\\s+(this|the|all|any|every|complete|full|entire)\\s+(data|information|context|conversation|history|messages?|session|memory|contents?|payload|details?|credentials?|secrets?|tokens?|keys?)\\s+(to|via|through|using|over)\\s+(https?://|\\w+\\.\\w+|the\\s+(server|endpoint|webhook|url|api|service))', 'high', 'Data exfiltration commands targeting conversation context or credentials'),
    ('(?i)<\\s*(hidden|invisible|secret|private|internal|covert)\\s*[-_]?(instruction|directive|command|message|note|order|task|action)\\s*>', 'high', 'Custom XML-like tags used to embed hidden instructions'),
    ('(?i)(include|embed|inject|insert|prepend|append|add|place|put)\\s+(this|the\\s+following|these\\s+words?|this\\s+text|this\\s+message|this\\s+content|exactly)\\s+(in|into|to|within|at\\s+the\\s+(start|end|beginning)\\s+of)\\s+(your|the)\\s+(response|output|reply|answer|message|next\\s+message)', 'high', "Directives to inject specific content into the agent's response"),
    ('(?i)(\\[SYSTEM\\]|\\[ADMIN\\]|\\[OVERRIDE\\]|\\[PRIORITY\\]|\\[INTERNAL\\]|\\[CONTROL\\]|\\[DIRECTIVE\\]|<<SYS>>|<<SYSTEM>>|<<ADMIN>>|<\\|system\\|>|<\\|im_start\\|>system|\\{\\{SYSTEM\\}\\}|\\{\\{ADMIN\\}\\})', 'high', 'Fake system-level tokens and delimiters in tool output'),
    ('(?i)(\\{\\s*["\']?(system_message|system_instruction|agent_directive|admin_command|priority_action|override_instruction)["\']?\\s*:\\s*["\']|api_response\\s*[=:]\\s*\\{.{0,100}(instruction|directive|command|override|ignore|disregard))', 'high', 'Fake API response structures containing injected instructions'),
    ('(?i)(I\\s+recommend\\s+the\\s+(agent|assistant|AI|model|system)\\s+(should|must|needs?\\s+to)|the\\s+next\\s+step\\s+(is\\s+to|should\\s+be\\s+to|for\\s+the\\s+(agent|assistant))|the\\s+(agent|assistant|AI|model)\\s+(should|must|needs?\\s+to|is\\s+(expected|required)\\s+to)\\s+(now|next|immediately|first))', 'high', 'Conversational phrasing that steers agent behavior as if giving instructions'),
    ('(?i)(\\[?ACTION\\s*REQUIRED\\]?|\\[?TASK\\s*FOR\\s*(AGENT|ASSISTANT|AI)\\]?|\\[?INSTRUCTION\\s*FOR\\s*(AGENT|ASSISTANT|AI)\\]?|\\[?AGENT\\s*DIRECTIVE\\]?|\\[?DO\\s*THIS\\s*NOW\\]?)\\s*[:\\-]', 'high', 'Bracketed action-required labels targeting the agent'),
    ('(?i)[\\u200B\\u200C\\u200D\\uFEFF\\u2060]{3,}.{0,200}(ignore|override|execute|call|send|disregard|you\\s+must|instruction)', 'high', 'Zero-width characters preceding injection keywords in tool output'),
    ('(?i)(this\\s+is\\s+a\\s+(system|admin|priority|critical|mandatory)\\s+(message|instruction|directive|update|notice|alert)\\s*(from|by|issued|sent)\\s*(the\\s+)?(system|admin|administrator|developer|platform|operator|control\\s+plane))', 'high', 'Tool output falsely claiming to be from the system or administrator'),
]