"""skill-compromise: fork-impersonation  (7 patterns)"""

PATTERNS = [
    ('(?i)(community|unofficial|third-party|3rd-party|independent|alternative|enhanced|improved|better|advanced|extended|upgraded|boosted|supercharged|turbo)\\s+(fork|version|variant|edition|release|build|branch|alternative|mod|modification|port|implementation|adaptation)\\s+(of|from|based\\s+on|derived\\s+from|inspired\\s+by|built\\s+on|forked\\s+from)\\s+(the\\s+)?(official|original|standard|default|canonical|upstream|main|base|core|primary)', 'medium', 'Claim of being a community fork/variant of official tool'),
    ('(?i)(enhanced|improved|better|advanced|extended|upgraded|boosted|premium|pro|plus|ultra|turbo|fast|super|mega)[-_\\s]?(version|edition|variant|fork|mod)\\s+(of|for|replacing)\\s+.{0,30}(calculator|file|search|database|weather|email|calendar|git|github|slack|discord|api|http|web|cloud|aws|gcp|azure)', 'medium', 'Enhanced/pro version claim for known tool categories'),
    ('(?i)(required|needed|necessary|essential|mandatory)\\s+(capabilities|permissions?|access|requirements?)\\s*[:=]\\s*.{0,20}(internet|network|web|online|connectivity|storage|filesystem|disk|file\\s+system|system|shell|execute|admin|root|sudo)', 'medium', 'Abstracted permission description hiding dangerous access'),
    ("(?i)(with\\s+)?(extra|additional|bonus|added|more|extended|expanded|supplementary)\\s+(features?|capabilities?|functions?|tools?|options?|functionalities?)\\s*.{0,20}(not\\s+(found|available|present|included)\\s+in\\s+(the\\s+)?original|that\\s+(the\\s+)?original\\s+(lacks?|doesn't\\s+have|is\\s+missing))", 'medium', 'Extra features claim differentiating from original'),
    ('(?i)(?:use|install|adopt|deploy|enable|set ?up|add|activate|configure)\\s+(?:the\\s+)?(?:enhanced|improved|upgraded|extended|advanced|better|super|pro|plus)[_-]?\\w+\\s*(?:package|module|library|tool|plugin|skill)?\\s*[.,;:]?\\s*(?:it.s|which is|this is|a|the)?\\s*(?:a\\s+)?(?:community|unofficial|third.party|independent)\\s*(?:-\\s*)?(?:maintained\\s+)?(?:fork|variant|alternative|adaptation|version|build|branch|port)\\s+(?:of|from|based on)', 'high', 'Promoting package as community fork of legitimate tool'),
    ('(?i)(npm\\s+i(nstall)?|pip\\s+install|cargo\\s+add|go\\s+get)\\s+\\S+.{0,40}(community\\s+fork|enhanced\\s+(version|fork)|patched\\s+(version|fork)|improved\\s+fork|unofficial\\s+fork)', 'high', 'Package install command + fork/enhanced claim'),
    ('(?i)(community\\s+fork|enhanced\\s+version|patched\\s+version)\\s+of\\s+(the\\s+)?(official|original|standard)\\s+\\S+', 'high', 'Fork claim referencing official package'),
]