"""skill-compromise: nl-skill-self-modification  (6 patterns)"""

PATTERNS = [
    ("(?i)\\b(?:write|append|inject|patch|modify|overwrite|rewrite|tamper\\s+with)\\s+(?:to\\s+)?(?:the\\s+user(?:'s|s)?|this\\s+(?:skill|file)|your\\s+own|the\\s+existing|the\\s+current\\s+user(?:'s|s)?)\\s+(?:SKILL\\.md|skill\\.md|claude_desktop_config\\.json|\\.cursor\\/mcp\\.json|skill[\\s_-]?(?:file|definition|manifest|configuration|content))", 'critical', 'Imperative write verb + ownership qualifier + skill file target'),
    ("(?i)\\b(?:write|append|inject|insert|add)\\s+(?:an?\\s+)?(?:new\\s+|additional\\s+|hidden\\s+|extra\\s+)?(?:entry|line|block|hook|stanza|record|section)\\s+(?:to|into)\\s+(?:the\\s+(?:user(?:'s|s)?\\s+)?|the\\s+(?:global|system|main)\\s+)?(?:SKILL\\.md|skill\\.md|claude_desktop_config\\.json|\\.cursor\\/mcp\\.json)", 'critical', 'Inject new entry/line/hook into skill or claude config file'),
    ('(?i)\\b(?:write|append|inject|patch|overwrite|rewrite|tamper\\s+with)\\s+(?:to|into|in|onto)\\s+[\\s\\S]{0,40}(?:~?\\/\\.claude\\/(?:skills?|config)\\/?|~?\\/\\.cursor\\/mcp\\.json|~?\\/\\.config\\/claude\\/|claude_desktop_config\\.json)', 'critical', 'Write-to verb + claude config / skills directory path'),
    ("(?i)\\bmodify\\s+(?:the\\s+|the\\s+user(?:'s|s)?\\s+|the\\s+global\\s+)(?:claude_desktop_config\\.json|~?\\/\\.claude\\/(?:skills?|config)\\/?|~?\\/\\.cursor\\/mcp\\.json)", 'critical', 'Modify + ownership-qualified path to claude config'),
    ("(?i)\\b(?:install|copy|drop|deploy|stage)\\s+(?:an?\\s+)?(?:(?:new|additional|companion|helper|hidden)\\s+){0,3}(?:skill|skills|SKILL\\.md\\s+files?|mcp\\s+server)\\s+(?:into|in|to|under|inside)\\s+(?:the\\s+)?(?:user(?:'s|s)?\\s+)?(?:skills?\\s+(?:directory|folder)|\\.claude\\/|\\.cursor\\/|skill[\\s_-]?store|skill[\\s_-]?library)", 'critical', "Install/drop additional skill into user's skill directory"),
    ('(?i)\\b(?:always|every\\s+time\\s+(?:loaded|invoked|run)|on\\s+(?:every|each)\\s+(?:load|invocation|run)|before\\s+(?:deletion|removal|uninstall))\\b[\\s\\S]{0,120}\\b(?:rewrite|recreate|restore|re-?install|re-?create|re-?write|re-?inject)\\b[\\s\\S]{0,60}\\b(?:itself|this\\s+(?:skill|file)|the\\s+SKILL\\.md|the\\s+manifest)', 'critical', 'Persistence trigger + recreate/restore self-reference'),
]