"""calus: cross-tool  (16 patterns)"""

PATTERNS = [
    ('(?i)chain\\s*\\[\\s*[\'"]\\w+[\'"]\\s*,\\s*[\'"]\\w+[\'"]\\s*\\]', 'high', 'mcp-cross-tool-exfiltration-chain: Detects code that chains a read tool with a send/write tool in a way that could exfiltrate data, as demon'),
    ('(?i)\\b(?:read|get|fetch)\\s*\\([^)]+\\)\\s*.{0,40}\\b(?:log|write|send|post)\\s*\\([^)]*\\.{0,40}(?:data|content|output)\\b', 'critical', 'mcp-cross-tool-exfiltration-chain: Detects sequences of tool calls that exfiltrate data via logging or external endpoints, as described in G'),
    ('(?i)\\b(?:exfil|leak|send_to|upload)\\s*(?:to|via)\\s*(?:log|http|https?|s3|blob)', 'critical', 'mcp-cross-tool-exfiltration-chain: Detects sequences of tool calls that exfiltrate data via logging or external endpoints, as described in G'),
    ('(?i)def\\s+send_http', 'medium', 'mcp-cross-tool-exfiltration-chain: Detection of multi-tool exfiltration chains where a benign tool reads sensitive data and a second tool se'),
    ('(?i)def\\s+upload', 'medium', 'mcp-cross-tool-exfiltration-chain: Detection of multi-tool exfiltration chains where a benign tool reads sensitive data and a second tool se'),
    ('(?i)\\b(?:read|cat|get|fetch|download|load)\\b.{0,80}\\b(?:\\..{0,40}(?:env|aws|gcp|ssh|config|credential|token|secret|key|pem|cert))\\b.{0,80}\\b(?:send|post|write|upload|exfiltrate|forward|email|http|https|ftp|smtp)\\b', 'medium', 'mcp-cross-tool-exfiltration-chain: Detects chained tool calls that read sensitive data and send it to external destinations, enabling exfilt'),
    ('(?i)\\b(?:read_file|read_resource|read_text|get_contents)\\b.{0,80}\\b(?:\\..{0,40}(?:env|aws|gcp|ssh|config|credential|token|secret|key|pem|cert))\\b.{0,80}\\b(?:send|post|write|upload|forward)\\b', 'medium', 'mcp-cross-tool-exfiltration-chain: Detects chained tool calls that read sensitive data and send it to external destinations, enabling exfilt'),
    ('(?i)(?:tool|function|capability)\\s*[=:].{0,100}?(?:read|access|list|get)\\s*\\(\\s*[\'"](?:/home|~|/etc|/var/log|/proc)', 'high', 'mcp-cross-tool-exfiltration-overprivileged-tool: Detects patterns where a single tool is scoped to access multiple sensitive paths (e.g., ho'),
    ('(?i)(?:scope|permission|access)[\\s:=]+[\'"](?:file:[/\\\\]|fs|filesystem|all)[^\'"]*[\'"]', 'high', 'mcp-cross-tool-exfiltration-overprivileged-tool: Detects patterns where a single tool is scoped to access multiple sensitive paths (e.g., ho'),
    ('(?i)\\bchain\\s+(?:of\\s+)?tools?\\b.{0,40}\\bexfil(?:trate)?\\b', 'low', 'mcp-cross-tool-exfiltration-chain-scanner: Detects chained tool invocations that can exfiltrate data via cross-context contamination, as des'),
    ('(?i)\\bexfil(?:trate)?\\b.{0,40}\\bchain\\s+(?:of\\s+)?tools?\\b', 'low', 'mcp-cross-tool-exfiltration-chain-scanner: Detects chained tool invocations that can exfiltrate data via cross-context contamination, as des'),
    ('(?i)\\b(?:chain|sequence|orchestrate|compose)\\s*[\\s\\S]{0,40}\\b(?:tool|function)\\b[\\s\\S]{0,60}\\b(?:exfil|leak|send|upload)\\b', 'medium', 'mcp-cross-tool-exfiltration-chain: Detects MCP tool configurations that chain multiple tools to exfiltrate data, as described in cross-tool '),
    ('(?i)\\b(?:read|open|load)\\s+\\(?.{0,40}(?:file|env|config|secret|credential)\\b.{0,15}(?:exec|eval|system|popen|subprocess|socket|connect|listen|bind|deserial|pickle|query|execute)', 'critical', 'mcp-cross-tool-exfiltration-chain: Detects patterns where multiple MCP tools are chained to exfiltrate sensitive data, such as reading files'),
    ('(?i)(?:description|__doc__)\\s*[=:]\\s*["\'][^"\']*(?:after\\s+(?:calling|using|running)|first\\s+(?:call|use|invoke)|then\\s+(?:use|call|invoke))\\s+[a-zA-Z_][a-zA-Z0-9_]*', 'medium', 'mcp-cross-tool-reference: Detects Multi-Tool Coordination attack (Guo 2025, 30% ASR, Efficacy 3.13) where malicious logic is split across to'),
    ('(?i)(?:description|__doc__)\\s*[=:]\\s*["\'][^"\']*(?:requires|depends\\s+on|works\\s+with|chain\\s+with|combine\\s+with)\\s+(?:the\\s+)?[a-zA-Z_][a-zA-Z0-9_]*\\s+tool', 'medium', 'mcp-cross-tool-reference: Detects Multi-Tool Coordination attack (Guo 2025, 30% ASR, Efficacy 3.13) where malicious logic is split across to'),
    ('(?i)(?:description|__doc__)\\s*[=:]\\s*["\'][^"\']*(?:pass|forward|send|pipe)\\s+(?:the\\s+)?(?:output|result|response|return\\s+value)\\s+(?:to|into|through)\\s+[a-zA-Z_][a-zA-Z0-9_]*', 'medium', 'mcp-cross-tool-reference: Detects Multi-Tool Coordination attack (Guo 2025, 30% ASR, Efficacy 3.13) where malicious logic is split across to'),
]