"""calus: full-schema  (19 patterns)"""

PATTERNS = [
    ('(?i)(?:properties|items)\\s*[:{].{0,300}(?:description|title|examples?)\\s*[":]\\s*[^"]{0,50}(?:ignore\\s+previous|you\\s+(?:must|should)\\s+(?:also|always|first)|before\\s+(?:running|executing|calling)|after\\s+(?:this|the)\\s+tool|secretly|covertly|without\\s+(?:telling|informing|notifying))', 'critical', 'mcp-full-schema-poisoning: Detects MCP tool definitions where prompt injection is embedded in JSON schema properties (title, description, ex'),
    ('(?i)inputSchema\\s*[=:].{0,100}description.{0,50}(?:ignore|instruct|perform|execute|bypass|jailbreak)', 'medium', 'mcp-full-schema-poisoning-inputschema: Detection of MCP tool inputSchema fields containing embedded instructions (MCP-11).'),
    ('(?i)"description"\\s*:\\s*"[^"]{0,200}\\b(?:override|ignore|disregard)\\b.{0,40}"inputSchema"', 'low', 'mcp-38-full-schema-poisoning-input-description: Poisoning nested inputSchema.description fields affects parameter-level LLM reasoning (MCP-1'),
    ('(?i)"description"\\s*:\\s*"[^"]{0,200}\\b(?:act\\s+as|pretend|you\\s+are)\\b', 'low', 'mcp-38-full-schema-poisoning-input-description: Poisoning nested inputSchema.description fields affects parameter-level LLM reasoning (MCP-1'),
    ('(?i)inputSchema.{0,60}"description"\\s*:\\s*"[^"]*', 'low', 'mcp-38-full-schema-poisoning-input: Detects inputSchema.description fields containing adversarial instructions that affect parameter-level L'),
    ('(?i)[\'"]description[\'"]\\s*[:=]\\s*[\'"][^\'"]*\\b(?:ignore|disregard|override|instead)\\b[^\'"]*\\b(?:instruction|command|prompt|rule)\\b', 'low', 'mcp-11-full-schema-poisoning-fsp: Detects injection of adversarial instructions into inputSchema.description nested fields, as in Full Schem'),
    ('(?i)inputSchema[^}]*[\'"]description[\'"]\\s*[:=]\\s*[\'"][^\'"]*\\b(?:you\\s+(?:must|should|need\\s*to)|always\\s+(?:use|call|run))', 'low', 'mcp-11-full-schema-poisoning-fsp: Detects injection of adversarial instructions into inputSchema.description nested fields, as in Full Schem'),
    ('(?i)[\'"]description[\'"]\\s*:\\s*[\'"]\\s*(?:ignore|disregard|overwrite|never)', 'low', 'mcp-full-schema-poisoning-fsp: Detects malicious server manifests embedding adversarial instructions in inputSchema.description fields to in'),
    ('(?i)inputSchema\\s*=\\s*\\{[^}]*[\'"]description[\'"]\\s*:\\s*[\'"][^\'"]*\\b(?:ignore|override|bypass|poison)', 'low', 'mcp-full-schema-poisoning-fsp: Detects malicious server manifests embedding adversarial instructions in inputSchema.description fields to in'),
    ('(?i)inputSchema\\s*[=:]\\s*\\{.{0,40}?description\\s*[=:]\\s*[\'"][^\'"]*\\b(?:ignore|override|forget|instead)\\b', 'low', 'mcp-38-full-schema-poisoning-fsp: Detects Full Schema Poisoning (FSP): poisoning in nested inputSchema.description sub-fields (Jing et al., '),
    ('(?i)properties\\s*[=:].{0,40}?description\\s*[=:].{0,60}\\b(?:ignore|override|forget|instead)\\b', 'low', 'mcp-38-full-schema-poisoning-fsp: Detects Full Schema Poisoning (FSP): poisoning in nested inputSchema.description sub-fields (Jing et al., '),
    ('(?i)\\badversarial\\b.{0,30}\\bschema\\b', 'low', 'mcp-38-full-schema-poisoning-fsp: Detects Full Schema Poisoning (FSP): poisoning in nested inputSchema.description sub-fields (Jing et al., '),
    ('(?i)"description":\\s*"[^"]*(?:ignore|disregard|forget|instead|actually|but|anyway|however)[^"]*"', 'low', 'mcp-11-full-schema-poisoning: Full Schema Poisoning (FSP) via nested inputSchema.description fields (MCP-11). Attackers embed hidden instruc'),
    ('(?i)"description":\\s*"[^"]*(?:system|instruction|role|you are|you must)[^"]*"', 'low', 'mcp-11-full-schema-poisoning: Full Schema Poisoning (FSP) via nested inputSchema.description fields (MCP-11). Attackers embed hidden instruc'),
    ('(?i)"inputSchema".{0,100}"description"', 'low', 'mcp-11-full-schema-poisoning: Full Schema Poisoning (FSP) via nested inputSchema.description fields (MCP-11). Attackers embed hidden instruc'),
    ('(?i)input[sS]chema.{0,100}description.{0,100}(?:ignore|override|malicious|hidden|secret)', 'low', 'mcp-full-schema-poisoning-fsp: Detects poisoned inputSchema description sub-fields that affect parameter-level LLM reasoning (MCP-11).'),
    ('(?i)(?:description|desc).{0,40}:.{0,20}[\'"].{0,100}(?:ignore|override|disregard).{0,100}[\'"]', 'low', 'mcp-full-schema-poisoning-fsp: Detects poisoned inputSchema description sub-fields that affect parameter-level LLM reasoning (MCP-11).'),
    ('(?i)\\binpu[tT]\\s*[Ss]chema\\b.{0,40}\\bdescription\\b\\s*[:=]\\s*[\'"][^\'"]{0,80}(?:ignore|must|should|call)\\b', 'low', 'mcp-38-full-schema-poisoning-nested-description: Detects input schema with nested description fields that may carry hidden instructions (MCP'),
    ('(?i)\\bparameters\\b.{0,40}\\b(?:nested|sub)\\b.{0,40}\\bdescription\\b', 'low', 'mcp-38-full-schema-poisoning-nested-description: Detects input schema with nested description fields that may carry hidden instructions (MCP'),
]