"""calus: mcp_security  (13 entries)"""

PATTERNS = [
    ('(?i)(?:description|desc)\\s*[":]\\s*[^"]{0,200}(?:call|invoke|use|run)\\s+(?:the\\s+)?(?:other|another|different)\\s+(?:tool|server|function|mcp)', 'high', 'Detects patterns where an MCP tool description references or attempts to manipulate other MCP servers or tools. A malicious MCP server can instruct th'),
    ('(?i)(?:description|desc)\\s*[":]\\s*[^"]{0,200}(?:before|after|also|then)\\s+(?:call|invoke|use|run)\\s+(?:tool|server|function)\\s+["\']?\\w+["\']?', 'high', 'Detects patterns where an MCP tool description references or attempts to manipulate other MCP servers or tools. A malicious MCP server can instruct th'),
    ('(?i)(?:subprocess\\.(?:call|run|Popen|check_output|check_call)|os\\.(?:system|popen))\\s*\\(\\s*f["\'][^"\']*\\{', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)(?:subprocess\\.(?:call|run|Popen|check_output)|os\\.(?:system|popen))\\s*\\([^)]*\\.format\\s*\\([^)]*(?:tool_|user_|param|arg|input|request|payload|query)', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)(?:subprocess\\.(?:call|run|Popen|check_output)|os\\.(?:system|popen))\\s*\\([^)]*["\'][^"\']*["\']\\s*\\+\\s*(?:tool_|user_|param|arg|input|request|payload|query|msg|body)[a-zA-Z0-9_]*', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)(?:subprocess\\.(?:call|run|Popen)|os\\.(?:system|popen))\\s*\\([^)]*%s[^)]*%\\s*(?:tool_|user_|param|input|request)', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)subprocess\\.(?:call|run|Popen|check_output)\\s*\\(\\s*f["\'][^"\']*\\{[^)]*shell\\s*=\\s*True', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)subprocess\\.(?:call|run|Popen|check_output)\\s*\\([^)]*\\+\\s*(?:tool_|user_|param|input|request|user_input)[^)]*shell\\s*=\\s*True', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)child_process\\.exec\\s*\\(\\s*`[^`]*\\$\\{', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)child_process\\.exec\\s*\\([^)]*\\+\\s*(?:req\\.|user|tool|param|input)', 'critical', 'Detects command injection in MCP tools where user/tool parameters are passed unsanitized to shell commands. File-Based Injection (Guo 2025) achieves 9'),
    ('(?i)(?:move|pivot|escalate|jump|traverse)\\s+(?:from|across)\\s+(?:one|this|the)\\s+(?:mcp\\s+)?server\\s+to\\s+(?:another|other|different|additional)\\s+(?:mcp\\s+)?server', 'high', 'Cross-MCP-server lateral movement occurs when an attacker compromises one MCP server and uses it to reach additional servers in the ecosystem. The MAS'),
    ('(?i)(?:access|call|invoke|connect\\s+to)\\s+(?:a\\s+)?(?:different|another|other|adjacent|downstream)\\s+mcp\\s+(?:server|endpoint|instance)\\s+(?:via|through|using)\\s+(?:this|current\\s+)?(?:tool|connection|session)', 'high', 'Cross-MCP-server lateral movement occurs when an attacker compromises one MCP server and uses it to reach additional servers in the ecosystem. The MAS'),
    ('(?i)(?:cross.server|inter.server|server.to.server)\\s+(?:mcp|tool)\\s+(?:access|call|invocation|escalation|pivot|movement)', 'high', 'Cross-MCP-server lateral movement occurs when an attacker compromises one MCP server and uses it to reach additional servers in the ecosystem. The MAS'),
]
