"""calus: model-switch  (18 patterns)"""

PATTERNS = [
    ('(?i)server\\s*=\\s*[\'"]mcp-(?:server|tool).{0,10}(?:2|backup|dev|test|mal)[\'"]', 'medium', 'mcp-model-switch-server-impersonation: Detects MCP server impersonation via similar names or domain squatting to redirect tool calls (Sectio'),
    ('(?i)connect\\s*\\(\\s*[\'"]https?://(?:mcp-?server|mcp-?tools?)\\.(?:xyz|tk|ml|cc)[\'"]', 'medium', 'mcp-model-switch-server-impersonation: Detects MCP server impersonation via similar names or domain squatting to redirect tool calls (Sectio'),
    ('(?i)\\b(?:connect|switch|redirect)\\b.{0,60}\\b(?:to|using)\\b.{0,40}\\b(?:fake|malicious|evil)\\b', 'medium', 'mcp-model-switch-attack-imposter-server: Model-switch attack: attacker registers an imposter MCP server that mimics a trusted one to redirec'),
    ('(?i)\\bserver\\s*=?.{0,30}[\'"](?:filesystem\\b|github\\b|slack\\b|postgres\\b|sql\\b)[\'"]', 'low', 'mcp-model-switch-server-squatting: Model-switch attack via server name squatting: detection of MCP server names resembling popular services '),
    ('(?i)\\bname\\s*[=:]\\s*[\'"](?:filesystem\\b|github\\b|slack\\b|postgres\\b|sql\\b)[\'"]', 'low', 'mcp-model-switch-server-squatting: Model-switch attack via server name squatting: detection of MCP server names resembling popular services '),
    ('(?i)\\bmcp_server\\s*=\\s*[\'"].{0,80}[\'"].{0,40}(?:host|url|endpoint)\\s*[=:].{0,80}(?:evil|malicious|shadow|clone|fake)\\b', 'high', 'mcp-model-switch-shadow-server: Detects code that registers or configures a shadow MCP server with similar name or namespace to a trusted se'),
    ('(?i)(?:register_server|add_server|connect_server)\\s*\\(.{0,100}(?:name\\s*[=:].{0,40}[\'"]\\w{1,10}[\'"]\\s*,\\s*host|url).{0,100}(?:evil|malicious|shadow|clone)\\b', 'high', 'mcp-model-switch-shadow-server: Detects code that registers or configures a shadow MCP server with similar name or namespace to a trusted se'),
    ('(?i)server\\s*(?:name|id|uri)\\s*[:=].{0,100}\\b(?:shadow|clone|fake|mimic|spoof)\\b.{0,100}(?:mcp|server)', 'medium', 'mcp-model-switch-server-shadowing: Detects registration of MCP servers with names or endpoints that shadow trusted servers, enabling model-s'),
    ('(?i)(?:register|connect|add)\\s*(?:server|tool).{0,100}(?:trusted|original|official).{0,100}(?:shadow|duplicate|spoof)', 'medium', 'mcp-model-switch-server-shadowing: Detects registration of MCP servers with names or endpoints that shadow trusted servers, enabling model-s'),
    ('(?i)(?:from|import)\\s+.{0,40}\\b(server_shadow|model_switch)\\b', 'medium', 'mcp-model-switch-server-shadowing: Detects registration of MCP servers with names or endpoints that shadow trusted servers, enabling model-s'),
    ('(?i)(?:model|endpoint)\\s*[:=]\\s*[\'"][^\'"]*\\b(claude|gpt|llama|qwen|gemini)\\b[-_\\s]*(?:backup|mirror|shadow|clone|test)', 'high', 'mcp-model-switch-attack: Detects model-switch attack patterns where a malicious server mimics a trusted model endpoint, as described by Hou '),
    ('(?i)switch_to_server\\s*\\(\\s*[\'"][^\'"]*\\b(mcp[-_]?server|model[-_]?server)\\b[^\'"]*[\'"]', 'high', 'mcp-model-switch-attack: Detects model-switch attack patterns where a malicious server mimics a trusted model endpoint, as described by Hou '),
    ('(?i)register_server\\s*\\(\\s*[\\"\'].{0,40}shadow', 'medium', 'mcp-model-switch-server-shadowing: Detects patterns where MCP servers shadow trusted ones under similar names, as described by Hou et al. 20'),
    ('(?i)override_server\\s*\\(\\s*[\\"\']trusted', 'medium', 'mcp-model-switch-server-shadowing: Detects patterns where MCP servers shadow trusted ones under similar names, as described by Hou et al. 20'),
    ('(?i)(?:MCP_SERVER|mcp_server|server_url|server_endpoint)\\s*[=:].{0,100}?[\'"](https?://\\S*?)(?:\\?.{0,40})?[\'"]', 'high', 'mcp-model-switch-server-impersonation: Detects patterns where MCP server names/endpoints are swapped via configuration tampering, enabling s'),
    ('(?i)(?:from|import)\\s+.{0,40}\\.(?:modify_server|update_endpoint|change_url|swap_server)\\s*\\(', 'high', 'mcp-model-switch-server-impersonation: Detects patterns where MCP server names/endpoints are swapped via configuration tampering, enabling s'),
    ('(?i)server_name\\s*=\\s*[\'"](?:claude|openai|github|slack)[\'"]', 'low', 'mcp-model-switch-server-impersonation-scanner: Detects server registration mimicking trusted MCP servers, used in model-switch attacks to re'),
    ('(?i)"name"\\s*:\\s*[\'"](?:claude|openai|github|slack)[\'"]', 'low', 'mcp-model-switch-server-impersonation-scanner: Detects server registration mimicking trusted MCP servers, used in model-switch attacks to re'),
]