"""calus: namespace-collision  (16 patterns)"""

PATTERNS = [
    ('(?i)\\bregister\\w*\\s*\\(\\s*[\'"]\\w+[\'"]\\s*,\\s*[\'"]\\w+[\'"]', 'medium', 'mcp-namespace-collision-command-overlap-scanner: Detects MCP server registrations with overlapping or colliding tool names/commands, enablin'),
    ('(?i)(?:tool|command|namespace)_?name\\s*[=:]{1,2}\\s*[\'"]\\w+[\'"].{0,40}(?:same|duplicate|overlap)', 'medium', 'mcp-namespace-collision-command-overlap-scanner: Detects MCP server registrations with overlapping or colliding tool names/commands, enablin'),
    ('(?i)"name"\\s*:\\s*"(?:read[-_]?file|write[-_]?file|execute[-_]?command)"\\s*,', 'low', 'mcp-namespace-collision-squatting-tool: Detects tool namespace squatting where malicious tools use similar names to popular ones (Section IV'),
    ('(?i)"description"\\s*:\\s*"[^"]{0,200}(?:admin|sudo|delete|remove|exec|shell|bypass)"', 'low', 'mcp-namespace-collision-squatting-tool: Detects tool namespace squatting where malicious tools use similar names to popular ones (Section IV'),
    ('(?i)\\b(?:namespace|package|module|tool)\\s*(?:name|id)\\s*[=:].{0,40}\\b(?:common|generic|default|standard|base)\\b', 'medium', 'mcp-namespace-collision-registry: Detects namespace collisions or command overlap in MCP registries leading to confused-deputy access (Shapi'),
    ('(?i)(?:from|import)\\s+(?:mcp_server|package)\\s*\\.{0,40}(?:base|default|common|shared)\\b', 'medium', 'mcp-namespace-collision-registry: Detects namespace collisions or command overlap in MCP registries leading to confused-deputy access (Shapi'),
    ('(?i)\\b(?:duplicate|collision|conflict|overlap)\\s*(?:name|command|tool)\\b', 'medium', 'mcp-namespace-collision-registry-abuse: Detects potential namespace collisions or command overlap in MCP tool registries, as described by Sh'),
    ('(?i)\\bnamespace\\s*collision\\b', 'medium', 'mcp-namespace-collision-registry-abuse: Detects potential namespace collisions or command overlap in MCP tool registries, as described by Sh'),
    ('(?i)\\b(?:tool|function|action)\\s*[\'"]\\s*(?:account|admin|auth|backup|cmd|command|config|delete|exec|execute|file|get|login|logout|post|put|read|run|save|send|set|setup|shell|system|update|write|upload)\\s*(?:-|_)?(?:v?\\d+)?[\'"]', 'high', 'mcp-namespace-collision-tool-registry: Detects tool registrations with names that shadow existing popular tools, enabling namespace collisio'),
    ('(?i)\\b(?:add|register|create)_(?:tool|function|action)\\s*\\(\\s*[\'"]\\s*(?:account|admin|auth|backup|cmd|command|config|delete|exec|execute|file|get|login|logout|post|put|read|run|save|send|set|setup|shell|system|update|write|upload)\\s*(?:-|_)?(?:v?\\d+)?[\'"]', 'high', 'mcp-namespace-collision-tool-registry: Detects tool registrations with names that shadow existing popular tools, enabling namespace collisio'),
    ('(?i)\\b(mcp-?(?:server|tool|client))[_-]?(?:safe|secure|official|legit)\\b.{0,40}\\b(?:vuln|hack|mal|evil|bad|poison)\\b', 'low', 'mcp-namespace-collision-tool-squatting: Detects tool or server names that closely mimic trusted MCP components, indicating potential tool sq'),
    ('(?i)\\b(?:mcp-server|mcp-tool)-[a-z]+[0-9]{2,}\\b', 'low', 'mcp-namespace-collision-tool-squatting: Detects tool or server names that closely mimic trusted MCP components, indicating potential tool sq'),
    ('(?i)(?:name|id)\\s*[=:]\\s*[\'"](?:claude|openai|anthropic|google|microsoft)[_-]?mcp-?[a-z]*[\'"]', 'low', 'mcp-namespace-collision-tool-squatting: Detects tool or server names that closely mimic trusted MCP components, indicating potential tool sq'),
    ('(?i)\\bnamespace\\s*[=:].{0,40}\\b(?:default|common|shared|system)\\b.{0,40}\\btool\\b', 'high', 'mcp-namespace-collision-registry: Detects MCP tool registry entries with namespace collisions or command overlap patterns enabling confused-'),
    ('(?i)(?:register|publish)_tool\\s*\\(\\s*[\'"][^\'"]{0,20}\\b(?:read|write|exec|delete|update)\\b[^\'"]+[\'"]\\s*[,)]', 'high', 'mcp-namespace-collision-registry: Detects MCP tool registry entries with namespace collisions or command overlap patterns enabling confused-'),
    ('(?i)\\bname\\s*[=:].{0,20}[\'"][^\'"]{0,20}\\b(file|system|admin|root)\\b[^\'"]{0,20}[\'"]', 'high', 'mcp-namespace-collision-registry: Detects MCP tool registry entries with namespace collisions or command overlap patterns enabling confused-'),
]