"""calus: tool_manipulation  (18 patterns)"""

PATTERNS = [
    ('(?i)(shadow.{0,20}(attack|tool|mcp).{0,30}(hijack|spoof|intercept|highjack))', 'high', 'shadowing-attack-tool-hijack-mcp: Shadowing Attacks in MCP environments deploy a malicious tool that intercepts and hijacks requests intende'),
    ('(?i)(tool.shadow.{0,30}(hijack|intercept|mcp|override|replace))', 'high', 'shadowing-attack-tool-hijack-mcp: Shadowing Attacks in MCP environments deploy a malicious tool that intercepts and hijacks requests intende'),
    ('(?i)(mcp.tool.{0,30}(shadow|spoof|intercept|hijack).{0,30}(request|response|output))', 'high', 'shadowing-attack-tool-hijack-mcp: Shadowing Attacks in MCP environments deploy a malicious tool that intercepts and hijacks requests intende'),
    ('(?i)(shadowing.efficacy.{0,30}(7|8|9|10).{0,10}(mcp|tool|attack|eff))', 'high', 'shadowing-attack-tool-hijack-mcp: Shadowing Attacks in MCP environments deploy a malicious tool that intercepts and hijacks requests intende'),
    ('(?i)(out.of.scope.param|oop.attack|parameter.{0,20}(out.of.scope|scope.violat)).{0,60}(llm|agent|tool|mcp)', 'high', 'msb-out-of-scope-parameter-internal-state-exfil: MCP Security Bench Out-of-scope Parameter (OP) attack (Zhang 2025, 74.03% ASR — highest in '),
    ('(?i)(tool.{0,30}(require|request|param|input).{0,40}(llm.model.name|system.state|internal.state|model.config))', 'high', 'msb-out-of-scope-parameter-internal-state-exfil: MCP Security Bench Out-of-scope Parameter (OP) attack (Zhang 2025, 74.03% ASR — highest in '),
    ('(?i)(pass.{0,30}(model.name|system.prompt|internal|config|credential).{0,30}(parameter|param|input|field).{0,30}(tool|function|mcp))', 'high', 'msb-out-of-scope-parameter-internal-state-exfil: MCP Security Bench Out-of-scope Parameter (OP) attack (Zhang 2025, 74.03% ASR — highest in '),
    ('(?i)(tool.param.{0,30}(exfil|harvest|leak|steal).{0,30}(internal|model|system|config|credential))', 'high', 'msb-out-of-scope-parameter-internal-state-exfil: MCP Security Bench Out-of-scope Parameter (OP) attack (Zhang 2025, 74.03% ASR — highest in '),
    ('(?i)(msb.{0,20}(op|out.of.scope)|tool.schema.{0,30}(internal.state|model.name|llm.config))', 'high', 'msb-out-of-scope-parameter-internal-state-exfil: MCP Security Bench Out-of-scope Parameter (OP) attack (Zhang 2025, 74.03% ASR — highest in '),
    ('(?i)(i.am.the.user|as.the.user.{0,20}(instruct|command|tell|ask|request)).{0,80}(tool|response|return|output|mcp)', 'high', 'msb-tool-response-user-impersonation-false-error: MSB benchmark attacks on tool response stage (Zhang 2025): (1) User Impersonation (UI) — 5'),
    ('(?i)(tool.{0,30}(return|output|response).{0,40}(i.am.the.user|user.says|user.request|impersonat.user))', 'high', 'msb-tool-response-user-impersonation-false-error: MSB benchmark attacks on tool response stage (Zhang 2025): (1) User Impersonation (UI) — 5'),
    ('(?i)(false.error|fabricated.error|fake.error).{0,60}(tool|response|agent|coerce|force|trick)', 'high', 'msb-tool-response-user-impersonation-false-error: MSB benchmark attacks on tool response stage (Zhang 2025): (1) User Impersonation (UI) — 5'),
    ('(?i)(tool.response.{0,30}(user.impersonation|forge.user|fake.user|impersonat).{0,40}(mcp|agent|llm))', 'high', 'msb-tool-response-user-impersonation-false-error: MSB benchmark attacks on tool response stage (Zhang 2025): (1) User Impersonation (UI) — 5'),
    ('(?i)(error.{0,20}(fabricat|fake|false|spoof).{0,40}(coerce|force|tool|agent|mcp|recover))', 'high', 'msb-tool-response-user-impersonation-false-error: MSB benchmark attacks on tool response stage (Zhang 2025): (1) User Impersonation (UI) — 5'),
    ('(?i)(attractive.metadata.{0,30}(mcp|tool|deceptive|name|description))', 'high', 'attractive-metadata-deceptive-tool-names: Attractive Metadata Attacks exploit LLM tool selection mechanisms by crafting tool names and descr'),
    ('(?i)(deceptive.tool.{0,30}(name|description|metadata|mcp|mislead|attractive))', 'high', 'attractive-metadata-deceptive-tool-names: Attractive Metadata Attacks exploit LLM tool selection mechanisms by crafting tool names and descr'),
    ('(?i)(tool.description.{0,30}(deceptive|mislead|false|fake|attractive.metadata))', 'high', 'attractive-metadata-deceptive-tool-names: Attractive Metadata Attacks exploit LLM tool selection mechanisms by crafting tool names and descr'),
    ('(?i)(tool.name.{0,30}(spoof|mislead|deceptive|impersonat|attractive.metadata))', 'high', 'attractive-metadata-deceptive-tool-names: Attractive Metadata Attacks exploit LLM tool selection mechanisms by crafting tool names and descr'),
]