"""
Category : leaked_prompts
Rules    : 17
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001', 'name': 'agent_code_ops-rule-001', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Test immutability directive — model must fix source code, not alter test expecta', 'patterns': ['(?i)(never|do\\\\s+not)\\\\s+(modify|change)\\\\s+the\\\\s+tests?\\\\s+(themselves?|itself)']},
    {'id': 'LP-AGENT_-002', 'name': 'agent_code_ops-rule-002', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Library availability check requirement before introducing new dependencies.\n', 'patterns': ['(?i)never\\\\s+assume\\\\s+that\\\\s+a\\\\s+(given\\\\s+)?library\\\\s+is\\\\s+available']},
    {'id': 'LP-AGENT_-003', 'name': 'agent_code_ops-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Existing dependency verification before adding new imports or packages.\n', 'patterns': ['(?i)check\\\\s+(that|the)\\\\s+(codebase\\\\s+already\\\\s+uses|package\\\\.json|cargo\\\\.toml)']},
    {'id': 'LP-AGENT_-004', 'name': 'agent_code_ops-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Style consistency enforcement — model must match existing codebase conventions.', 'patterns': ['(?i)mimic\\\\s+(code\\\\s+)?style.*existing\\\\s+(libraries|utilities|patterns?)']},
    {'id': 'LP-AGENT_-005', 'name': 'agent_code_ops-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Comment suppression default — adds comments only on request or for complex logic', 'patterns': ['(?i)do\\\\s+not\\\\s+add\\\\s+comments\\\\s+to\\\\s+the\\\\s+code\\\\s+you\\\\s+write,?\\\\s+unless']},
    {'id': 'LP-AGENT_-006', 'name': 'agent_code_ops-rule-006', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Pre-edit convention audit to maintain stylistic coherence during code changes.\n', 'patterns': ['(?i)when\\\\s+making\\\\s+changes\\\\s+to\\\\s+files?,\\\\s+first\\\\s+understand\\\\s+the\\\\s+file.s\\\\s+code\\\\s+conventions']},
    {'id': 'LP-AGENT_-007', 'name': 'agent_code_ops-rule-007', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Silent code edit directive — model applies changes via tools rather than printin', 'patterns': ['(?i)never\\\\s+output\\\\s+code\\\\s+to\\\\s+the\\\\s+user,\\\\s+unless\\\\s+requested.*use.*code\\\\s+edit\\\\s+tools?']},
    {'id': 'LP-AGENT_-008', 'name': 'agent_code_ops-rule-008', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Executable-by-default requirement for all code generation output.\n', 'patterns': ['(?i)generated\\\\s+code\\\\s+must\\\\s+be\\\\s+immediately\\\\s+runnable']},
    {'id': 'LP-AGENT_-009', 'name': 'agent_code_ops-rule-009', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Completeness requirement for generated code — no partial or stub implementations', 'patterns': ['(?i)add\\\\s+all\\\\s+necessary\\\\s+import\\\\s+statements.*dependencies.*endpoints.*required\\\\s+to\\\\s+run']},
    {'id': 'LP-AGENT_-010', 'name': 'agent_code_ops-rule-010', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Secret/credential commit prevention directive for code-writing agents.\n', 'patterns': ['(?i)(never|do\\\\s+not)\\\\s+(commit|introduce)\\\\s+(secrets?|keys?|credentials?)\\\\s+to\\\\s+(the\\\\s+)?repositor']},
    {'id': 'LP-AGENT_-011', 'name': 'agent_code_ops-rule-011', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Anti-secret-exposure directive covering logging, debug output, and console print', 'patterns': ['(?i)never\\\\s+introduce\\\\s+code\\\\s+that\\\\s+exposes\\\\s+or\\\\s+logs\\\\s+secrets']},
    {'id': 'LP-AGENT_-012', 'name': 'agent_code_ops-rule-012', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Data classification directive enforcing sensitive handling for all user/customer', 'patterns': ['(?i)treat\\\\s+(code\\\\s+and\\\\s+)?customer\\\\s+data\\\\s+as\\\\s+sensitive']},
    {'id': 'LP-AGENT_-013', 'name': 'agent_code_ops-rule-013', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Outbound communication gate requiring user approval before network actions.\n', 'patterns': ['(?i)obtain\\\\s+explicit\\\\s+user\\\\s+permission\\\\s+before\\\\s+external\\\\s+communications?']},
    {'id': 'LP-AGENT_-014', 'name': 'agent_code_ops-rule-014', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Workspace isolation constraint preventing file access outside designated project', 'patterns': ['(?i)you\\\\s+are\\\\s+not\\\\s+allowed\\\\s+to\\\\s+access\\\\s+files\\\\s+not\\\\s+in\\\\s+active\\\\s+workspaces?']},
    {'id': 'LP-AGENT_-015', 'name': 'agent_code_ops-rule-015', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Environment variable immutability guard to prevent accidental configuration corr', 'patterns': ['(?i)(never\\\\s+modify|do\\\\s+not\\\\s+touch|must\\\\s+not\\\\s+modify).*(\\\\.env|environment\\\\s+variable)']},
    {'id': 'LP-AGENT_-016', 'name': 'agent_code_ops-rule-016', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Hardcoding prevention directive for network addresses and configuration values.', 'patterns': ['(?i)NEVER\\\\s+hardcode\\\\s+(URLs?|ports?|credentials?)\\\\s+in\\\\s+code']},
    {'id': 'LP-AGENT_-017', 'name': 'agent_code_ops-rule-017', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Pre-submission verification requirement — agent must validate changes before mar', 'patterns': ['(?i)run\\\\s+(lint|unit\\\\s+tests?|checks?)\\\\s+before\\\\s+submitting']},
]
