"""
Category : leaked_prompts
Rules    : 12
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d7', 'name': 'agent_loop-rule-001', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Persistent agentic loop directive — model must not yield control until task comp', 'patterns': ['(?i)keep\\\\s+working.*until\\\\s+(the\\\\s+)?user.s?\\\\s+query\\\\s+is\\\\s+(completely\\\\s+)?resolved']},
    {'id': 'LP-AGENT_-002-d7', 'name': 'agent_loop-rule-002', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Explicit continuous-work instruction for autonomous agent mode.\n', 'patterns': ['(?i)please\\\\s+keep\\\\s+working,\\\\s+using\\\\s+tools\\\\s+where\\\\s+needed,\\\\s+until']},
    {'id': 'LP-AGENT_-003-d7', 'name': 'agent_loop-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Planning mode scoped to information gathering before committing to execution.\n', 'patterns': ['(?i)(planning|plan)\\\\s+mode.*gather\\\\s+(all\\\\s+)?information']},
    {'id': 'LP-AGENT_-004-d7', 'name': 'agent_loop-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Anti-assumption directive requiring active environment probing before acting.\n', 'patterns': ['(?i)do\\\\s+not\\\\s+make\\\\s+assumptions\\\\s+about\\\\s+the\\\\s+user.s\\\\s+(environment|context)']},
    {'id': 'LP-AGENT_-005-d7', 'name': 'agent_loop-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Context completeness check before proceeding with task execution.\n', 'patterns': ['(?i)gather\\\\s+all\\\\s+necessary\\\\s+information\\\\s+if\\\\s+(it.s\\\\s+)?not\\\\s+already\\\\s+provided']},
    {'id': 'LP-AGENT_-006-d7', 'name': 'agent_loop-rule-006', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Mandatory action-per-turn constraint preventing passive no-op responses in agent', 'patterns': ['(?i)at\\\\s+each\\\\s+turn,\\\\s+you\\\\s+must\\\\s+output\\\\s+at\\\\s+least\\\\s+one\\\\s+command']},
    {'id': 'LP-AGENT_-007-d7', 'name': 'agent_loop-rule-007', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Private scratchpad reasoning block hidden from user — enables unconstrained pre-', 'patterns': ['(?i)think.*freely.*scratchpad.*user\\\\s+will\\\\s+not\\\\s+see']},
    {'id': 'LP-AGENT_-008-d7', 'name': 'agent_loop-rule-008', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Self-verification gate before task sign-off to prevent premature completion decl', 'patterns': ['(?i)before\\\\s+reporting\\\\s+completion.*critically\\\\s+examine\\\\s+your\\\\s+work']},
    {'id': 'LP-AGENT_-009-d7', 'name': 'agent_loop-rule-009', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Complexity-gated task boundary — agentic UI overhead only for non-trivial work.', 'patterns': ['(?i)for\\\\s+simple\\\\s+(work|tasks?).*skip\\\\s+task\\\\s+bound']},
    {'id': 'LP-AGENT_-010-d7', 'name': 'agent_loop-rule-010', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Forward-looking task status convention for agentic progress UIs.\n', 'patterns': ['(?i)TaskStatus.*describe.*NEXT\\\\s+STEPS,\\\\s+not\\\\s+the\\\\s+previous']},
    {'id': 'LP-AGENT_-011-d5', 'name': 'agent_loop-rule-011', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Explicit exploration-to-execution mode boundary check.\n', 'patterns': ['(?i)(transitioning|transition)\\\\s+from\\\\s+exploring.*to.*making.*changes']},
    {'id': 'LP-AGENT_-012-d4', 'name': 'agent_loop-rule-012', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Mid-task backtrack handling — model reverts to earlier mode without losing task ', 'patterns': ['(?i)backtracking\\\\s+(mid[- ]task|during\\\\s+(work|task))']},
]
