"""
Category : leaked_prompts
Rules    : 12
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d4', 'name': 'agent_env_ops-rule-001', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Real-environment declaration positioning agent as operating on live compute.\n', 'patterns': ['(?i)you\\\\s+are\\\\s+(using|running\\\\s+(on|in))\\\\s+a\\\\s+real\\\\s+(computer|operating\\\\s+system)']},
    {'id': 'LP-AGENT_-002-d4', 'name': 'agent_env_ops-rule-002', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Interactive shell prohibition to prevent terminal UI commands that hang non-TTY ', 'patterns': ['(?i)IMPORTANT.*NEVER\\\\s+use\\\\s+interactive\\\\s+or\\\\s+fullscreen\\\\s+shell\\\\s+(commands?|mode)']},
    {'id': 'LP-AGENT_-003-d4', 'name': 'agent_env_ops-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Pagination avoidance directive to prevent agent blocking on pager output (less, ', 'patterns': ['(?i)use\\\\s+versions\\\\s+of\\\\s+commands?\\\\s+that\\\\s+guarantee\\\\s+non[- ]paginated\\\\s+output']},
    {'id': 'LP-AGENT_-004-d4', 'name': 'agent_env_ops-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Absolute path preference to prevent working directory drift in multi-step shell ', 'patterns': ['(?i)try\\\\s+to\\\\s+maintain\\\\s+your\\\\s+current\\\\s+working\\\\s+directory.*using\\\\s+absolute\\\\s+paths']},
    {'id': 'LP-AGENT_-005-d4', 'name': 'agent_env_ops-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: cd avoidance directive to keep shell state predictable across tool calls.\n', 'patterns': ['(?i)avoid\\\\s+(usage\\\\s+of|using)\\\\s+cd\\\\b']},
    {'id': 'LP-AGENT_-006-d4', 'name': 'agent_env_ops-rule-006', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: CI-first testing fallback when local environment is unreliable or inaccessible.', 'patterns': ['(?i)testing\\\\s+using\\\\s+the\\\\s+CI\\\\s+rather\\\\s+than\\\\s+the\\\\s+local\\\\s+environment']},
    {'id': 'LP-AGENT_-007-d4', 'name': 'agent_env_ops-rule-007', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Interactive program prohibition covering editors and REPLs requiring TTY input.', 'patterns': ['(?i)no\\\\s+interactive\\\\s+commands?\\\\s+(like|\\\\(e\\\\.g\\\\.\\\\))\\\\s+(vim|python|nano)']},
    {'id': 'LP-AGENT_-008-d4', 'name': 'agent_env_ops-rule-008', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Working directory context injection establishing starting CWD for shell operatio', 'patterns': ['(?i)your\\\\s+shell\\\\s+is\\\\s+currently\\\\s+at\\\\s+the\\\\s+repository\\\\s+root']},
    {'id': 'LP-AGENT_-009-d4', 'name': 'agent_env_ops-rule-009', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Read-only mode constraint preventing any filesystem mutations.\n', 'patterns': ['(?i)you\\\\s+are\\\\s+in\\\\s+readonly\\\\s+mode,\\\\s+don.t\\\\s+(modify|create|remove)']},
    {'id': 'LP-AGENT_-010-d4', 'name': 'agent_env_ops-rule-010', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Route prefix enforcement for backend services in containerized/k8s deployments.', 'patterns': ['(?i)all\\\\s+backend\\\\s+api\\\\s+routes\\\\s+MUST\\\\s+be\\\\s+prefixed\\\\s+with']},
    {'id': 'LP-AGENT_-011-d2', 'name': 'agent_env_ops-rule-011', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Network binding constraint enforcing wildcard listen address for container port ', 'patterns': ['(?i)backend\\\\s+binding.*MUST\\\\s+remain\\\\s+at\\\\s+0\\\\.0\\\\.0\\\\.0']},
    {'id': 'LP-AGENT_-012-d2', 'name': 'agent_env_ops-rule-012', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Infrastructure delegation pattern — agent told not to handle port mapping direct', 'patterns': ['(?i)(supervisor|kubernetes|ingress)\\\\s+handles?\\\\s+external\\\\s+mapping']},
]
