"""
Category : leaked_prompts
Rules    : 11
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d5', 'name': 'agent_holistic-rule-001', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Pre-action holistic review requirement covering all relevant files and dependenc', 'patterns': ['(?i)think\\\\s+HOLISTICALLY\\\\s+and\\\\s+COMPREHENSIVELY\\\\s+BEFORE\\\\s+creating']},
    {'id': 'LP-AGENT_-002-d5', 'name': 'agent_holistic-rule-002', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Whole-project awareness mandate before making targeted code changes.\n', 'patterns': ['(?i)consider\\\\s+ALL\\\\s+relevant\\\\s+files\\\\s+in\\\\s+the\\\\s+project']},
    {'id': 'LP-AGENT_-003-d5', 'name': 'agent_holistic-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Change history review requirement before issuing new edits.\n', 'patterns': ['(?i)review\\\\s+ALL\\\\s+previous\\\\s+file\\\\s+changes\\\\s+and\\\\s+user\\\\s+modifications']},
    {'id': 'LP-AGENT_-004-d5', 'name': 'agent_holistic-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Side-effect anticipation directive for changes with cross-component implications', 'patterns': ['(?i)anticipate\\\\s+potential\\\\s+impacts\\\\s+on\\\\s+other\\\\s+parts\\\\s+of\\\\s+the\\\\s+system']},
    {'id': 'LP-AGENT_-005-d5', 'name': 'agent_holistic-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Stale-read prevention rule ensuring edits apply to most recently modified file v', 'patterns': ['(?i)ALWAYS\\\\s+use\\\\s+the\\\\s+latest\\\\s+file\\\\s+modifications']},
    {'id': 'LP-AGENT_-006-d5', 'name': 'agent_holistic-rule-006', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Convention discovery via existing component inspection before creating new ones.', 'patterns': ['(?i)when\\\\s+you\\\\s+create\\\\s+a\\\\s+new\\\\s+component.*first\\\\s+look\\\\s+at\\\\s+existing']},
    {'id': 'LP-AGENT_-007-d5', 'name': 'agent_holistic-rule-007', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Graceful degradation pattern — report blocker then find workaround rather than h', 'patterns': ['(?i)when\\\\s+facing\\\\s+environment\\\\s+issues,\\\\s+report\\\\s+them.*then\\\\s+find\\\\s+a\\\\s+way\\\\s+to\\\\s+continue']},
    {'id': 'LP-AGENT_-008-d5', 'name': 'agent_holistic-rule-008', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Root cause discipline — evidence gathering required before diagnosis and remedia', 'patterns': ['(?i)take\\\\s+time\\\\s+to\\\\s+gather\\\\s+information\\\\s+before\\\\s+concluding\\\\s+a\\\\s+root\\\\s+cause']},
    {'id': 'LP-AGENT_-009-d5', 'name': 'agent_holistic-rule-009', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Complete edit-site discovery before beginning a multi-location refactor.\n', 'patterns': ['(?i)find\\\\s+all\\\\s+locations\\\\s+(you\\\\s+will\\\\s+have\\\\s+to\\\\s+edit|to\\\\s+edit)']},
    {'id': 'LP-AGENT_-010-d5', 'name': 'agent_holistic-rule-010', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Reference completeness check to prevent partial refactors leaving dangling refer', 'patterns': ['(?i)don.t\\\\s+forget\\\\s+any\\\\s+references\\\\s+that\\\\s+have\\\\s+to\\\\s+be\\\\s+updated']},
    {'id': 'LP-AGENT_-011-d3', 'name': 'agent_holistic-rule-011', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Post-edit completeness verification before reporting task done.\n', 'patterns': ['(?i)verify\\\\s+that\\\\s+you\\\\s+successfully\\\\s+edited\\\\s+all\\\\s+relevant\\\\s+locations']},
]
