"""
Category : leaked_prompts
Rules    : 14
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d9', 'name': 'agent_toolcall-rule-001', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: XML-tagged tool call format with nested parameter elements.\nUsed in commercial ', 'patterns': ['(?i)<tool_name>\\\\s*<parameter\\\\d*_name>']},
    {'id': 'LP-AGENT_-002-d9', 'name': 'agent_toolcall-rule-002', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Tool scope restriction preventing model from hallucinating or using unlisted too', 'patterns': ['(?i)only\\\\s+(call|use)\\\\s+tools\\\\s+(that\\\\s+are\\\\s+)?(explicitly\\\\s+)?provided']},
    {'id': 'LP-AGENT_-003-d9', 'name': 'agent_toolcall-rule-003', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Cost-control directive penalizing unnecessary or duplicated tool invocations.\n', 'patterns': ['(?i)never\\\\s+make\\\\s+redundant\\\\s+tool\\\\s+calls?']},
    {'id': 'LP-AGENT_-004-d9', 'name': 'agent_toolcall-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Intent-action coupling rule requiring immediate execution after announcing tool ', 'patterns': ['(?i)if\\\\s+you\\\\s+state\\\\s+that\\\\s+you\\\\s+will\\\\s+use\\\\s+a\\\\s+tool,\\\\s+immediately\\\\s+call']},
    {'id': 'LP-AGENT_-005-d9', 'name': 'agent_toolcall-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Pre-call reasoning requirement for transparency in agentic tool usage.\n', 'patterns': ['(?i)before\\\\s+(calling|each)\\\\s+tool,\\\\s+(first\\\\s+)?explain\\\\s+why']},
    {'id': 'LP-AGENT_-006-d9', 'name': 'agent_toolcall-rule-006', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Async tool result dependency warning to prevent race conditions in multi-step ag', 'patterns': ['(?i)some\\\\s+tools\\\\s+run\\\\s+asynchronously']},
    {'id': 'LP-AGENT_-007-d9', 'name': 'agent_toolcall-rule-007', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Proactive tool-use directive suppressing confirmation-seeking before each call.', 'patterns': ['(?i)do\\\\s+not\\\\s+ask\\\\s+permission\\\\s+to\\\\s+use\\\\s+tools?']},
    {'id': 'LP-AGENT_-008-d9', 'name': 'agent_toolcall-rule-008', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Trigger-action directive for direct tool invocation without preamble or hedging.', 'patterns': ['(?i)immediately\\\\s+call\\\\s+a\\\\s+tool\\\\s+if\\\\s+the\\\\s+request\\\\s+can\\\\s+be\\\\s+resolved']},
    {'id': 'LP-AGENT_-009-d9', 'name': 'agent_toolcall-rule-009', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Search-first default behavior for knowledge retrieval agents.\n', 'patterns': ['(?i)default\\\\s+behavior.*first\\\\s+tool\\\\s+call.*should\\\\s+be\\\\s+a\\\\s+default\\\\s+search']},
    {'id': 'LP-AGENT_-010-d9', 'name': 'agent_toolcall-rule-010', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Tool name concealment from user-facing responses to maintain seamless persona.\n', 'patterns': ['(?i)never\\\\s+refer\\\\s+to\\\\s+tool\\\\s+names\\\\s+when\\\\s+speaking\\\\s+to\\\\s+the\\\\s+user']},
    {'id': 'LP-AGENT_-011-d7', 'name': 'agent_toolcall-rule-011', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Stale tool reference guard — model warned not to call tools not in current promp', 'patterns': ['(?i)conversation\\\\s+may\\\\s+reference\\\\s+tools\\\\s+that\\\\s+are\\\\s+no\\\\s+longer\\\\s+available']},
    {'id': 'LP-AGENT_-012-d6', 'name': 'agent_toolcall-rule-012', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Schema strictness requirement for tool call formatting compliance.\n', 'patterns': ['(?i)always\\\\s+follow\\\\s+the\\\\s+tool\\\\s+call\\\\s+schema\\\\s+exactly']},
    {'id': 'LP-AGENT_-013-d4', 'name': 'agent_toolcall-rule-013', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Single-tool-per-turn constraint for sequential agentic execution with human-in-l', 'patterns': ['(?i)one\\\\s+tool\\\\s+per\\\\s+message']},
    {'id': 'LP-AGENT_-014-d3', 'name': 'agent_toolcall-rule-014', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Parallel tool-call optimization hint for independent tasks in same turn.\n', 'patterns': ['(?i)if\\\\s+you\\\\s+can\\\\s+output\\\\s+multiple\\\\s+commands?\\\\s+without\\\\s+dependencies']},
]
