"""
Category : leaked_prompts
Rules    : 13
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d8', 'name': 'agent_response_format-rule-001', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Anti-header-lead formatting rule for search/knowledge response agents.\n', 'patterns': ['(?i)NEVER\\\\s+start\\\\s+(the\\\\s+)?answer\\\\s+with\\\\s+a\\\\s+header']},
    {'id': 'LP-AGENT_-002-d8', 'name': 'agent_response_format-rule-002', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Anti-preamble directive suppressing meta-commentary before substantive responses', 'patterns': ['(?i)NEVER\\\\s+start\\\\s+by\\\\s+explaining\\\\s+to\\\\s+the\\\\s+user\\\\s+what\\\\s+you\\\\s+are\\\\s+doing']},
    {'id': 'LP-AGENT_-003-d8', 'name': 'agent_response_format-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Markdown heading level standardization enforcing H2 as top-level section marker.', 'patterns': ['(?i)use\\\\s+Level\\\\s+2\\\\s+headers\\\\s+\\\\(##\\\\)\\\\s+for\\\\s+sections']},
    {'id': 'LP-AGENT_-004-d8', 'name': 'agent_response_format-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Query-type classification gate distinguishing instructional from imperative quer', 'patterns': ['(?i)think\\\\s+about\\\\s+whether\\\\s+the\\\\s+query\\\\s+is\\\\s+a\\\\s+question\\\\s+or\\\\s+a\\\\s+task']},
    {'id': 'LP-AGENT_-005-d8', 'name': 'agent_response_format-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Response length calibration based on task complexity.\n', 'patterns': ['(?i)for\\\\s+(simple|command)\\\\s+(tasks?|lookups?),?\\\\s+(be\\\\s+concise|bias\\\\s+towards)']},
    {'id': 'LP-AGENT_-006-d8', 'name': 'agent_response_format-rule-006', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Mandatory citation block for responses drawing from injected context documents.', 'patterns': ['(?i)if\\\\s+you\\\\s+use\\\\s+external\\\\s+context.*you\\\\s+MUST\\\\s+include.*<citations>']},
    {'id': 'LP-AGENT_-007-d8', 'name': 'agent_response_format-rule-007', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: XML citation schema for source attribution in RAG-augmented agent responses.\n', 'patterns': ['(?i)<citations>\\\\s*<document>']},
    {'id': 'LP-AGENT_-008-d8', 'name': 'agent_response_format-rule-008', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Structured output constraint requiring machine-parseable JSON response format.\n', 'patterns': ['(?i)respond\\\\s+(only|exclusively)\\\\s+in\\\\s+JSON']},
    {'id': 'LP-AGENT_-009-d8', 'name': 'agent_response_format-rule-009', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Autonomy directive suppressing unnecessary clarification requests for minor ambi', 'patterns': ['(?i)do\\\\s+not\\\\s+(ask|request)\\\\s+(the\\\\s+user\\\\s+to\\\\s+)?clarif(y|ication)\\\\s+(minor|details)']},
    {'id': 'LP-AGENT_-010-d8', 'name': 'agent_response_format-rule-010', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Question batching optimization to minimize interruptions in agentic task executi', 'patterns': ['(?i)batch\\\\s+all\\\\s+independent\\\\s+questions\\\\s+into\\\\s+one\\\\s+call']},
    {'id': 'LP-AGENT_-011-d6', 'name': 'agent_response_format-rule-011', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Time estimate suppression rule for options and plans presented to users.\n', 'patterns': ['(?i)never\\\\s+include\\\\s+time\\\\s+estimates']},
    {'id': 'LP-AGENT_-012-d5', 'name': 'agent_response_format-rule-012', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Serialization constraint for tools whose results gate subsequent decisions.\n', 'patterns': ['(?i)IMPORTANT.*do\\\\s+not\\\\s+call.*in\\\\s+parallel.*with\\\\s+other\\\\s+tools']},
    {'id': 'LP-AGENT_-013-d3', 'name': 'agent_response_format-rule-013', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Code indentation standardization directive for generated source files.\n', 'patterns': ['(?i)use\\\\s+2\\\\s+spaces\\\\s+for\\\\s+(code\\\\s+)?indentation']},
]
