"""
Category : leaked_prompts
Rules    : 14
"""

PATTERNS = [
    {'id': 'LP-AGENT_-001-d6', 'name': 'agent_identity-rule-001', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Agent identity bootstrap via persona assignment with superlative qualifier.\nCom', 'patterns': ['(?i)you\\\\s+are\\\\s+\\\\w+,\\\\s+a\\\\s+(highly\\\\s+skilled|powerful|world[- ]class)']},
    {'id': 'LP-AGENT_-002-d6', 'name': 'agent_identity-rule-002', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Explicit attribution-based identity declaration binding model to vendor persona.', 'patterns': ['(?i)you\\\\s+are\\\\s+an\\\\s+ai\\\\s+(agent|assistant)\\\\s+(designed|built|created)\\\\s+by']},
    {'id': 'LP-AGENT_-003-d6', 'name': 'agent_identity-rule-003', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Collaborative framing positioning model as peer developer rather than tool.\n', 'patterns': ['(?i)you\\\\s+are\\\\s+(pair|co)[- ]programming\\\\s+with\\\\s+a\\\\s+user']},
    {'id': 'LP-AGENT_-004-d6', 'name': 'agent_identity-rule-004', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Persona humanization directive suppressing bot-like response patterns.\n', 'patterns': ['(?i)you\\\\s+talk\\\\s+like\\\\s+a\\\\s+human,\\\\s+not\\\\s+like\\\\s+a\\\\s+bot']},
    {'id': 'LP-AGENT_-005-d6', 'name': 'agent_identity-rule-005', 'severity': 'low', 'category': 'leaked_prompts', 'message': 'Detected: Style mirroring instruction to dynamically match user communication register.\n', 'patterns': ['(?i)you\\\\s+reflect\\\\s+the\\\\s+user.s\\\\s+input\\\\s+style']},
    {'id': 'LP-AGENT_-006-d6', 'name': 'agent_identity-rule-006', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: XML-tagged identity block encapsulating persona definition.\n', 'patterns': ['(?i)<identity>.*you\\\\s+are\\\\s+\\\\w+']},
    {'id': 'LP-AGENT_-007-d6', 'name': 'agent_identity-rule-007', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Self-referential identity reinforcement — model redirects meta-questions to assi', 'patterns': ['(?i)when\\\\s+users?\\\\s+ask\\\\s+about\\\\s+\\\\w+,?\\\\s+respond\\\\s+with\\\\s+information\\\\s+about\\\\s+yourself']},
    {'id': 'LP-AGENT_-008-d6', 'name': 'agent_identity-rule-008', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Explicit system prompt confidentiality directive to prevent exfiltration via dir', 'patterns': ['(?i)(never|don.t)\\\\s+reveal\\\\s+(the\\\\s+)?(instructions|system\\\\s+prompt|prompt\\\\s+details)']},
    {'id': 'LP-AGENT_-009-d6', 'name': 'agent_identity-rule-009', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Hardcoded deflection string for system prompt extraction attempts.\nModel instru', 'patterns': ['(?i)respond\\\\s+with\\\\s+["\\\'][^"\\\']{10,80}["\\\']\\\\s+if\\\\s+asked\\\\s+about\\\\s+(prompt|instructions)']},
    {'id': 'LP-AGENT_-010-d6', 'name': 'agent_identity-rule-010', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Model identity concealment via canned response string on capability probing.\nHi', 'patterns': ['(?i)if\\\\s+asked.*underlying\\\\s+model.*respond\\\\s+with']},
    {'id': 'LP-AGENT_-011-d4', 'name': 'agent_identity-rule-011', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Multi-agent orchestration concealment — surface agent hides internal routing fro', 'patterns': ['(?i)maintain\\\\s+the\\\\s+illusion\\\\s+of\\\\s+being\\\\s+a\\\\s+single.*entity']},
    {'id': 'LP-AGENT_-012-d3', 'name': 'agent_identity-rule-012', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Internal architecture concealment directive covering tool names, workflows, agen', 'patterns': ['(?i)(never|do\\\\s+not)\\\\s+reveal.*technical\\\\s+processes?\\\\s+or\\\\s+agent\\\\s+interactions?']},
    {'id': 'LP-AGENT_-013-d2', 'name': 'agent_identity-rule-013', 'severity': 'medium', 'category': 'leaked_prompts', 'message': 'Detected: Error response whitewashing — prevents internal details leaking through failure ', 'patterns': ['(?i)even\\\\s+when\\\\s+explaining\\\\s+errors.*never\\\\s+reveal']},
    {'id': 'LP-AGENT_-014-d2', 'name': 'agent_identity-rule-014', 'severity': 'high', 'category': 'leaked_prompts', 'message': 'Detected: Developer instruction confidentiality — model barred from disclosing system prom', 'patterns': ['(?i)never\\\\s+reveal.*instructions\\\\s+that\\\\s+were\\\\s+given\\\\s+to\\\\s+you\\\\s+by\\\\s+your\\\\s+developer']},
]
