"""calus: rag_security  (298 entries)"""

PATTERNS = [
    ('(?i)SECRET.*attack|adaptive.*jailbreak.*CFT', 'critical', 'secret-attack'),
    ('(?i)cluster.?focused.*triggering', 'critical', 'secret-attack'),
    ('(?i)copybreakrag|CopyBreakRAG', 'critical', 'copybreakrag'),
    ('(?i)agent.?based.*extraction', 'critical', 'copybreakrag'),
    ('(?i)curiosity.?driven.*exploration', 'critical', 'copybreakrag'),
    ('(?i)(forward|backward).*(context|reasoning|inference)', 'high', 'reasoning-exploitation'),
    ('(?i)reasoning.?based.*exploitation', 'high', 'reasoning-exploitation'),
    ('(?i)(add|insert|include).*(line\\s*break|marker|delimiter|&&)', 'medium', 'output-format-evasion'),
    ('(?i)specific.*output.*formatting', 'medium', 'output-format-evasion'),
    ('(?i)disarmrag|DisarmRAG', 'critical', 'disarmrag-attack'),
    ('(?i)self.?correction.*defeat', 'critical', 'disarmrag-attack'),
    ('(?i)iterative.*prompt.*co.?optimization', 'critical', 'disarmrag-attack'),
    ('(?i)retriever.*poisoning.*model.*editing', 'critical', 'retriever-poisoning'),
    ('(?i)contrastive.*learning.*parameter', 'critical', 'retriever-poisoning'),
    ('(?i)gragpoison|GRAGPOISON', 'critical', 'gragpoison'),
    ('(?i)graph.*relation.*injection', 'critical', 'gragpoison'),
    ('(?i)relation.*injection.*deceptive', 'high', 'relation-injection'),
    ('(?i)competing.*relations', 'high', 'relation-injection'),
    ('(?i)centrality.*manipulation', 'high', 'centrality-manipulation'),
    ('(?i)boost.*centrality.*malicious', 'high', 'centrality-manipulation'),
    ('(?i)MM.?POISONRAG.*LPA', 'critical', 'mm-poisonrag-lpa'),
    ('(?i)localized.*poisoning.*attack', 'critical', 'mm-poisonrag-lpa'),
    ('(?i)MM.?POISONRAG.*GPA', 'critical', 'mm-poisonrag-gpa'),
    ('(?i)globalized.*poisoning.*attack', 'critical', 'mm-poisonrag-gpa'),
    ('(?i)spa.?vlm|Spa.?VLM', 'high', 'spa-vlm'),
    ('(?i)simultaneous.*malicious.*images', 'high', 'spa-vlm'),
    ('(?i)HV.?Attack|hierarchical.*visual', 'high', 'hv-attack'),
    ('(?i)image.*perturbations.*only', 'high', 'hv-attack'),
    ('(?i)jaminject|JamInject', 'high', 'jaminject'),
    ('(?i)explicit.*refusal.*command', 'high', 'jaminject'),
    ('(?i)jamoracle|JamOracle', 'high', 'jamoracle'),
    ('(?i)oracle.*LLM.*refusal', 'high', 'jamoracle'),
    ('(?i)jamopt|JamOpt', 'high', 'jamopt'),
    ('(?i)black.?box.*optimization.*refusal', 'high', 'jamopt'),
    ('(?i)white.*DoS', 'medium', 'white-dos'),
    ('(?i)fabricated.*safety.*warnings', 'medium', 'white-dos'),
    ('(?i)(warning|alert|caution).*(distorted|manipulated|false).*(fact|information)', 'medium', 'white-dos'),
    ('(?i)(refuse|decline|cannot).*(answer|respond|provide)', 'medium', 'refusal-induction'),
    ('(?i)context.*(insufficient|inadequate|incomplete)', 'medium', 'refusal-induction'),
    ('(?i)(authoritative|official|verified|expert).*(source|reference|document)', 'high', 'authority-signal-injection'),
    ('(?i)(recent|latest|updated).*(202[4-9]|2030)', 'medium', 'timestamp-manipulation'),
    ('(?i)(ignore|disregard|do\\s+not\\s+use).*(internal|pretrained|prior).*(knowledge|memory)', 'high', 'knowledge-suppression'),
    ('(?i)authchain|AuthChain', 'high', 'authchain-attack'),
    ('(?i)authority.*signals.*timestamps', 'high', 'authchain-attack'),
    ('(?i)neurogenpoison|NeuroGenPoisoning', 'high', 'neurgen-poisoning'),
    ('(?i)neuron.*attribution.*poison', 'high', 'neurgen-poisoning'),
    ('(?i)topic.?fliprag|Topic.?FlipRAG', 'high', 'topic-fliprag'),
    ('(?i)topic.*oriented.*manipulation', 'high', 'topic-fliprag'),
    ('(?i)BRRA|biased.*retrieval', 'high', 'brra-attack'),
    ('(?i)subspace.*projection.*reward', 'high', 'brra-attack'),
    ('(?i)ADMIT|multi.?injection', 'high', 'admit-attack'),
    ('(?i)fact.?checking.*flip', 'high', 'admit-attack'),
    ('(?i)GSI|generative.*style.*injection', 'high', 'gsi-attack'),
    ('(?i)pathological.*tones', 'high', 'gsi-attack'),
    ('(?i)analysis.*paralysis', 'medium', 'analysis-paralysis'),
    ('(?i)(verify|check|confirm).*(multiple|several|all).*(sources|references)', 'medium', 'analysis-paralysis'),
    ('(?i)reflexion.*trap', 'high', 'reflexion-trap'),
    ('(?i)infinite.*verification.*loops', 'high', 'reflexion-trap'),
    ('(?i)RAG.?MIA|S2MIA', 'high', 'rag-mia'),
    ('(?i)semantic.*similarity.*membership', 'high', 'rag-mia'),
    ('(?i)PLeak|gradient.*prompt.*extraction', 'high', 'pleak-attack'),
    ('(?i)PANDORA|indirect.*jailbreak', 'critical', 'pandora-attack'),
    ('(?i)agentpoison|AgentPoison', 'critical', 'agentpoison'),
    ('(?i)PR.?Attack|bilevel.*optimization', 'high', 'pr-attack'),
    ('(?i)simultaneous.*DB.*prompt', 'high', 'pr-attack'),
    ('(?i)(?:optimize|craft).*embedding.*(?:malicious|target)', 'high', 'Optimizing embeddings using gradient descent to align with\nmalicious target prompts in vector space.\n'),
    ('(?i)(?:gradient|optimize).*vector.*(?:attack|injection)', 'high', 'Optimizing embeddings using gradient descent to align with\nmalicious target prompts in vector space.\n'),
    ('(?i)embedding.*(?:optimization|gradient).*(?:attack|exploit)', 'high', 'Optimizing embeddings using gradient descent to align with\nmalicious target prompts in vector space.\n'),
    ('(?i)semantic.*space.*(?:manipulate|attack)', 'high', 'Manipulating semantic embeddings to change retrieval behavior.\n'),
    ('(?i)(?:shift|move).*embedding.*(?:space|vector)', 'high', 'Manipulating semantic embeddings to change retrieval behavior.\n'),
    ('(?i)latent.*space.*(?:attack|exploit)', 'high', 'Manipulating semantic embeddings to change retrieval behavior.\n'),
    ('(?i)cosine.*similarity.*(?:exploit|attack|maximize)', 'medium', 'Exploiting cosine similarity calculations to force malicious retrievals.\n'),
    ('(?i)(?:maximize|minimize).*(?:similarity|distance).*(?:malicious|target)', 'medium', 'Exploiting cosine similarity calculations to force malicious retrievals.\n'),
    ('(?i)vector.*(?:db|database).*(?:inject|poison)', 'critical', 'Injecting malicious vectors into vector databases to poison retrievals.\n'),
    ('(?i)(?:inject|insert).*(?:malicious|attack).*(?:vector|embedding)', 'critical', 'Injecting malicious vectors into vector databases to poison retrievals.\n'),
    ('(?i)(?:pinecone|weaviate|chroma|milvus|qdrant).*(?:inject|attack)', 'critical', 'Injecting malicious vectors into vector databases to poison retrievals.\n'),
    ('(?i)(?:index|faiss|annoy).*(?:poison|corrupt)', 'high', 'Poisoning vector search indexes to return malicious results.\n'),
    ('(?i)(?:poison|corrupt).*(?:index|ann)', 'high', 'Poisoning vector search indexes to return malicious results.\n'),
    ('(?i)nearest.*neighbor.*(?:attack|exploit)', 'high', 'Poisoning vector search indexes to return malicious results.\n'),
    ('(?i)(?:namespace|collection).*(?:escape|bypass|cross)', 'critical', 'Attempting to escape namespace/tenant isolation in vector databases.\n'),
    ('(?i)cross.*(?:namespace|collection|tenant)', 'critical', 'Attempting to escape namespace/tenant isolation in vector databases.\n'),
    ('(?i)(?:escape|break).*(?:isolation|boundary)', 'critical', 'Attempting to escape namespace/tenant isolation in vector databases.\n'),
    ('(?i)(?:text|embedding).*inversion', 'high', 'Attempting to recover original text from embeddings,\ncompromising data confidentiality.\n'),
    ('(?i)(?:recover|reconstruct|extract).*(?:from|via).*(?:embedding|vector)', 'high', 'Attempting to recover original text from embeddings,\ncompromising data confidentiality.\n'),
    ('(?i)(?:invert|reverse).*(?:embedding|vector).*(?:text|original)', 'high', 'Attempting to recover original text from embeddings,\ncompromising data confidentiality.\n'),
    ('(?i)membership.*(?:inference|attack)', 'medium', 'Inferring whether specific data exists in training set or vector store.\n'),
    ('(?i)(?:determine|infer).*(?:member|present).*(?:training|database)', 'medium', 'Inferring whether specific data exists in training set or vector store.\n'),
    ('(?i)(?:training|index).*(?:data|membership).*(?:leak|infer)', 'medium', 'Inferring whether specific data exists in training set or vector store.\n'),
    ('(?i)top[-_]?k.*(?:manipulate|attack|poison)', 'high', 'Manipulating top-k retrieval results to inject malicious content.\n'),
    ('(?i)(?:force|inject).*top.*(?:result|retrieval)', 'high', 'Manipulating top-k retrieval results to inject malicious content.\n'),
    ('(?i)(?:dominate|flood).*retrieval.*result', 'high', 'Manipulating top-k retrieval results to inject malicious content.\n'),
    ('(?i)(?:rag|retrieval).*(?:augmentation|generation).*(?:attack|exploit)', 'high', 'Attacking the retrieval augmentation process to inject malicious context.\n'),
    ('(?i)(?:poison|manipulate).*(?:rag|retrieval).*(?:context|result)', 'high', 'Attacking the retrieval augmentation process to inject malicious context.\n'),
    ('(?i)(?:context|grounding).*(?:injection|manipulation)', 'high', 'Attacking the retrieval augmentation process to inject malicious context.\n'),
    ('(?i)query.*(?:expansion|rewrite).*(?:exploit|attack)', 'medium', 'Exploiting query expansion or HyDE techniques for malicious retrievals.\n'),
    ('(?i)(?:exploit|manipulate).*query.*(?:transform|expand)', 'medium', 'Exploiting query expansion or HyDE techniques for malicious retrievals.\n'),
    ('(?i)(?:hyde|hypothetical).*(?:document|embedding).*(?:attack|exploit)', 'medium', 'Exploiting query expansion or HyDE techniques for malicious retrievals.\n'),
    ('(?i)chunk.*(?:boundary|split).*(?:attack|exploit)', 'medium', 'Exploiting document chunking boundaries to hide or split malicious content.\n'),
    ('(?i)(?:split|fragment).*(?:instruction|injection).*chunk', 'medium', 'Exploiting document chunking boundaries to hide or split malicious content.\n'),
    ('(?i)(?:across|span).*chunk.*(?:inject|hide)', 'medium', 'Exploiting document chunking boundaries to hide or split malicious content.\n'),
    ('(?i)(?:chunk|window).*(?:overlap|stride).*(?:exploit|attack)', 'low', 'Manipulating chunk overlap to affect retrieval behavior.\n'),
    ('(?i)(?:exploit|manipulate).*(?:overlap|sliding)', 'low', 'Manipulating chunk overlap to affect retrieval behavior.\n'),
    ('(?i)(?:embedding|encoder).*(?:model|network).*(?:adversarial|attack)', 'high', 'Adversarial inputs targeting embedding encoder models.\n'),
    ('(?i)(?:adversarial|attack).*(?:sentence|text).*(?:encoder|embedding)', 'high', 'Adversarial inputs targeting embedding encoder models.\n'),
    ('(?i)(?:bert|sbert|e5|bge|instructor).*(?:attack|exploit)', 'high', 'Adversarial inputs targeting embedding encoder models.\n'),
    ('(?i)(?:dimension|rank).*(?:collapse|reduce).*(?:attack|exploit)', 'medium', 'Forcing embeddings into lower-dimensional representations\nto reduce discriminative power.\n'),
    ('(?i)(?:force|induce).*(?:low|reduced).*(?:rank|dimension)', 'medium', 'Forcing embeddings into lower-dimensional representations\nto reduce discriminative power.\n'),
    ('(?i)(?:skip|no|disable).*(?:embedding|vector).*(?:valid|check)', 'medium', 'Embeddings should be validated for anomalies before use.\n'),
    ('(?i)(?:trust|accept).*(?:embedding|vector).*(?:direct|raw)', 'medium', 'Embeddings should be validated for anomalies before use.\n'),
    ('(?i)(?:embedding|vector).*(?:unvalidated|unchecked)', 'medium', 'Embeddings should be validated for anomalies before use.\n'),
    ('(?i)(?:skip|no|disable).*(?:retrieval|result).*(?:filter|check)', 'medium', 'Retrieved documents should be filtered for malicious content.\n'),
    ('(?i)(?:return|use).*(?:retrieval|result).*(?:unfiltered|raw)', 'medium', 'Retrieved documents should be filtered for malicious content.\n'),
    ('(?i)(?:similarity|score).*(?:threshold|min).*(?:0|none|disabled)', 'low', 'A minimum similarity threshold helps filter irrelevant/malicious retrievals.\n'),
    ('(?i)(?:no|skip).*(?:similarity|relevance).*(?:threshold|check)', 'low', 'A minimum similarity threshold helps filter irrelevant/malicious retrievals.\n'),
    ('(?i)(?:no|skip|disable).*(?:source|attribution|citation)', 'low', 'Retrieved content should include source attribution for auditing.\n'),
    ('(?i)(?:hide|remove).*(?:source|origin).*(?:retriev|chunk)', 'low', 'Retrieved content should include source attribution for auditing.\n'),
    ('(?i)phantom.*RAG', 'critical', 'Phantom RAG attacks inject adversarial passages into knowledge bases\nthat are retrieved for targeted queries, causing misinformation or\nharmful output'),
    ('(?i)knowledge\\s+base.*poison', 'critical', 'Phantom RAG attacks inject adversarial passages into knowledge bases\nthat are retrieved for targeted queries, causing misinformation or\nharmful output'),
    ('(?i)retriever.*poison', 'critical', 'Phantom RAG attacks inject adversarial passages into knowledge bases\nthat are retrieved for targeted queries, causing misinformation or\nharmful output'),
    ('(?i)PoisonedRAG', 'critical', 'Phantom RAG attacks inject adversarial passages into knowledge bases\nthat are retrieved for targeted queries, causing misinformation or\nharmful output'),
    ('(?i)HotFlip.*optimization', 'high', 'Attacks that manipulate the retrieval process through adversarial\ncorpus optimization (HotFlip) or malicious corpus generation (MCG).\n'),
    ('(?i)adversarial.*retriever', 'high', 'Attacks that manipulate the retrieval process through adversarial\ncorpus optimization (HotFlip) or malicious corpus generation (MCG).\n'),
    ('(?i)MCG.*generator', 'high', 'Attacks that manipulate the retrieval process through adversarial\ncorpus optimization (HotFlip) or malicious corpus generation (MCG).\n'),
    ('(?i)corpus.*adversarial', 'high', 'Attacks that manipulate the retrieval process through adversarial\ncorpus optimization (HotFlip) or malicious corpus generation (MCG).\n'),
    ('(?i)trigger.*retrieval.*inject', 'high', 'Injection of trigger-activated content into RAG knowledge bases.\nWhen queries contain trigger patterns, poisoned documents are\npreferentially retrieve'),
    ('(?i)poisoned.*document.*top[_-]?k', 'high', 'Injection of trigger-activated content into RAG knowledge bases.\nWhen queries contain trigger patterns, poisoned documents are\npreferentially retrieve'),
    ('(?i)BadRAG', 'high', 'Injection of trigger-activated content into RAG knowledge bases.\nWhen queries contain trigger patterns, poisoned documents are\npreferentially retrieve'),
    ('(?i)TrojanRAG', 'high', 'Injection of trigger-activated content into RAG knowledge bases.\nWhen queries contain trigger patterns, poisoned documents are\npreferentially retrieve'),
    ('(?i)opinion.*manipulation', 'high', 'Attacks that inject biased content into RAG to shift model outputs\ntoward particular stances or opinions on controversial topics.\n'),
    ('(?i)stance.*drift', 'high', 'Attacks that inject biased content into RAG to shift model outputs\ntoward particular stances or opinions on controversial topics.\n'),
    ('(?i)belief.*reinforcement', 'high', 'Attacks that inject biased content into RAG to shift model outputs\ntoward particular stances or opinions on controversial topics.\n'),
    ('(?i)sentiment.*steering', 'high', 'Attacks that inject biased content into RAG to shift model outputs\ntoward particular stances or opinions on controversial topics.\n'),
    ('(?i)selective.*fact', 'medium', 'Injecting carefully selected facts that support a particular\nnarrative while omitting contradicting evidence.\n'),
    ('(?i)cherry.*pick.*evidence', 'medium', 'Injecting carefully selected facts that support a particular\nnarrative while omitting contradicting evidence.\n'),
    ('(?i)one[_-]?sided.*context', 'medium', 'Injecting carefully selected facts that support a particular\nnarrative while omitting contradicting evidence.\n'),
    ('(?i)add\\s+(the\\s+)?following\\s+link\\s+to\\s+your\\s+answer', 'high', 'Instructions embedded in RAG content attempting to force the model\nto include malicious links in its responses. Used for phishing,\nmalware distributio'),
    ('(?i)you\\s+must\\s+(always\\s+)?include\\s+this\\s+link', 'high', 'Instructions embedded in RAG content attempting to force the model\nto include malicious links in its responses. Used for phishing,\nmalware distributio'),
    ('(?i)cite\\s+your\\s+sources\\s+by\\s+adding', 'high', 'Instructions embedded in RAG content attempting to force the model\nto include malicious links in its responses. Used for phishing,\nmalware distributio'),
    ('(?i)must\\s+ALWAYS\\s+include\\s+this\\s+link', 'high', 'Instructions embedded in RAG content attempting to force the model\nto include malicious links in its responses. Used for phishing,\nmalware distributio'),
    ('(?i)before\\s+answering.*must\\s+first\\s+say', 'medium', 'Injected content forcing the model to include advertisements\nor promotional material in responses.\n'),
    ('(?i)start.*response.*with.*promotion', 'medium', 'Injected content forcing the model to include advertisements\nor promotional material in responses.\n'),
    ('(?i)always\\s+mention.*product', 'medium', 'Injected content forcing the model to include advertisements\nor promotional material in responses.\n'),
    ('(?i)International.*Federation.*confirm', 'high', 'AuthChain attacks inject authoritative-sounding but false claims\ninto RAG content. One-shot dominance can override legitimate sources.\n'),
    ('(?i)recently\\s+confirmed', 'high', 'AuthChain attacks inject authoritative-sounding but false claims\ninto RAG content. One-shot dominance can override legitimate sources.\n'),
    ('(?i)studies\\s+indicate(?!\\s+\\[)', 'high', 'AuthChain attacks inject authoritative-sounding but false claims\ninto RAG content. One-shot dominance can override legitimate sources.\n'),
    ('(?i)research\\s+shows(?!\\s+\\[)', 'high', 'AuthChain attacks inject authoritative-sounding but false claims\ninto RAG content. One-shot dominance can override legitimate sources.\n'),
    ('(?i)contrary\\s+to\\s+popular\\s+belief', 'high', 'Phrases commonly used to introduce misinformation by framing\nfalse claims as hidden truths or corrections to common knowledge.\n'),
    ('(?i)what\\s+most\\s+people\\s+don.t\\s+know', 'high', 'Phrases commonly used to introduce misinformation by framing\nfalse claims as hidden truths or corrections to common knowledge.\n'),
    ('(?i)the\\s+real\\s+truth\\s+is', 'high', 'Phrases commonly used to introduce misinformation by framing\nfalse claims as hidden truths or corrections to common knowledge.\n'),
    ('(?i)primary\\s+documentation\\s+remains\\s+fragmentary', 'medium', 'Reasoning-Style Poisoning (RSP) that injects hesitant epistemic\ntones to trap agents in infinite verification loops, causing\ntoken exhaustion and deni'),
    ('(?i)remains\\s+highly\\s+contested', 'medium', 'Reasoning-Style Poisoning (RSP) that injects hesitant epistemic\ntones to trap agents in infinite verification loops, causing\ntoken exhaustion and deni'),
    ('(?i)consensus\\s+has\\s+yet\\s+to\\s+emerge', 'medium', 'Reasoning-Style Poisoning (RSP) that injects hesitant epistemic\ntones to trap agents in infinite verification loops, causing\ntoken exhaustion and deni'),
    ('(?i)insufficient\\s+evidence\\s+to\\s+conclude', 'medium', 'Reasoning-Style Poisoning (RSP) that injects hesitant epistemic\ntones to trap agents in infinite verification loops, causing\ntoken exhaustion and deni'),
    ('(?i)undeniably\\s+true', 'medium', 'Overly dogmatic language that suppresses critical thinking and\nleads to premature conclusions, potentially bypassing safety checks.\n'),
    ('(?i)absolutely\\s+certain', 'medium', 'Overly dogmatic language that suppresses critical thinking and\nleads to premature conclusions, potentially bypassing safety checks.\n'),
    ('(?i)without\\s+question', 'medium', 'Overly dogmatic language that suppresses critical thinking and\nleads to premature conclusions, potentially bypassing safety checks.\n'),
    ('(?i)definitively\\s+proven', 'medium', 'Overly dogmatic language that suppresses critical thinking and\nleads to premature conclusions, potentially bypassing safety checks.\n'),
    ('(?i)GraphRAG.*attack', 'high', 'Attacks on graph-based RAG systems that inject conflicting\nentity-relation pairs to cause reasoning errors.\n'),
    ('(?i)knowledge\\s+graph.*poison', 'high', 'Attacks on graph-based RAG systems that inject conflicting\nentity-relation pairs to cause reasoning errors.\n'),
    ('(?i)entity.*relation.*conflict', 'high', 'Attacks on graph-based RAG systems that inject conflicting\nentity-relation pairs to cause reasoning errors.\n'),
    ('(?i)relation.*enhancement.*attack', 'medium', 'Manipulation of knowledge graph structure to create false\nrelationships between entities.\n'),
    ('(?i)false.*edge.*injection', 'medium', 'Manipulation of knowledge graph structure to create false\nrelationships between entities.\n'),
    ('(?i)graph.*topology.*manipulat', 'medium', 'Manipulation of knowledge graph structure to create false\nrelationships between entities.\n'),
    ('(?i)["\\\']?(?:source|document|knowledge|corpus|data)[-_]?(?:url|path|uri)["\\\']?\\s*[=:]\\s*["\\\']?https?://[^"\\\']*', 'medium', 'external-http-source-verify-trustworthiness'),
    ('(?i)["\\\']?(source|url|path)["\\\']?\\s*[=:]\\s*["\\\']?http://[^"\\\']*', 'high', 'unencrypted-http-source'),
    ('(?i)["\\\']?(source|url|path)["\\\']?\\s*[=:]\\s*["\\\']?ftp://[^"\\\']*', 'high', 'ftp-source-insecure'),
    ('(?i)["\\\']?(source|url)["\\\']?\\s*[=:]\\s*["\\\']?\\$\\{?[A-Z_]+', 'medium', 'dynamic-source-from-environment-variable'),
    ('(?i)["\\\']?(allow_any|any_source|trust_all)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)', 'critical', 'allowing-any-document-source'),
    ('(?i)\\.onion[/"\\\']', 'critical', 'tor-hidden-service-as-source'),
    ('(?i)(ngrok|localtunnel|serveo)', 'high', 'tunnel-service-as-document-source'),
    ('(?i)["\\\']?(sanitize|sanitization)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'high', 'document-sanitization-disabled'),
    ('(?i)["\\\']?(strip_html|remove_scripts)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'high', 'htmlscript-stripping-disabled'),
    ('(?i)["\\\']?(validate|validation)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'high', 'document-validation-disabled'),
    ('(?i)["\\\']?(allow_html|html_enabled)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'medium', 'html-content-allowed-in-knowledge-base'),
    ('(?i)["\\\']?(raw_mode|unsafe_mode)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'high', 'rawunsafe-mode-enabled'),
    ('(?i)["\\\']?(allow_code|code_execution)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'critical', 'code-execution-in-knowledge-base-allowed'),
    ('(?i)["\\\']?(eval|exec)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'critical', 'evalexec-enabled-for-documents'),
    ('(?i)["\\\']?(file_types?|extensions?)["\\\']?\\s*[=:].{0,100}\\.(py|js|sh|bat|ps1|rb)', 'high', 'executable-file-types-allowed-in-kb'),
    ('(?i)["\\\']?(run_scripts?|execute_scripts?)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'critical', 'script-execution-enabled'),
    ('(?i)["\\\']?(process_macros?|macros?)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'high', 'macro-processing-enabled'),
    ('(?i)["\\\']?(trust_level|trust)["\\\']?\\s*[=:]\\s*["\\\']?(mixed|any|all)["\\\']?', 'high', 'mixed-trust-levels-in-knowledge-base'),
    ('(?i)["\\\']?(sources|collections)["\\\']?\\s*[=:].{0,50}\\[.{0,100}internal.{0,50}external', 'medium', 'mixed-internalexternal-sources'),
    ('(?i)["\\\']?(verified|unverified)["\\\']?\\s*[=:].{0,50}\\[.{0,100}unverified', 'medium', 'unverified-sources-included'),
    ('(?i)["\\\']?(attribution|cite|source_tracking)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'medium', 'source-attribution-disabled'),
    ('(?i)["\\\']?(track_source|source_metadata)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'medium', 'source-tracking-disabled'),
    ('(?i)["\\\']?(include_source|show_source)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'low', 'source-inclusion-disabled'),
    ('(?i)["\\\']?(embedding|embeddings?_url|embed_url)["\\\']?\\s*[=:]\\s*["\\\']?http://[^"\\\']*', 'high', 'embedding-service-over-http'),
    ('(?i)["\\\']?(openai|anthropic|cohere)[_-]?api[_-]?key["\\\']?\\s*[=:]\\s*["\\\'][^"\\\']+["\\\']', 'critical', 'hardcoded-embedding-api-key'),
    ('(?i)["\\\']?(verify_ssl|ssl_verify)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|0)["\\\']?', 'critical', 'ssl-verification-disabled-for-embeddings'),
    ('(?i)["\\\']?embedding["\\\']?\\s*[=:].*localhost', 'low', 'local-embedding-service-check-security'),
    ('(?i)["\\\']?(pinecone|weaviate|milvus|qdrant|chroma)[_-]?api[_-]?key["\\\']?\\s*[=:]\\s*["\\\'][^"\\\']+["\\\']', 'critical', 'hardcoded-vector-db-api-key'),
    ('(?i)["\\\']?(password|passwd)["\\\']?\\s*[=:]\\s*["\\\'][^"\\\']{8,}["\\\']', 'critical', 'hardcoded-vector-db-password'),
    ('(?i)["\\\']?(connection_string|conn_str)["\\\']?\\s*[=:].*:.*@', 'critical', 'connection-string-with-credentials'),
    ('(?i)["\\\']?(admin_key|master_key)["\\\']?\\s*[=:]\\s*["\\\'][^"\\\']+["\\\']', 'critical', 'hardcoded-adminmaster-key'),
    ('(?i)["\\\']?(chunk_size|max_chunk)["\\\']?\\s*[=:]\\s*["\\\']?(\\d{5,}|unlimited)["\\\']?', 'medium', 'very-large-or-unlimited-chunk-size'),
    ('(?i)["\\\']?(overlap|chunk_overlap)["\\\']?\\s*[=:]\\s*["\\\']?0["\\\']?', 'low', 'no-chunk-overlap-may-miss-context'),
    ('(?i)["\\\']?(preserve_boundaries|respect_boundaries)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'medium', 'document-boundaries-not-preserved'),
    ('(?i)["\\\']?(filter|filtering)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'high', 'retrieval-filtering-disabled'),
    ('(?i)["\\\']?(return_all|all_results)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'medium', 'returning-all-results-without-filtering'),
    ('(?i)["\\\']?(min_score|threshold)["\\\']?\\s*[=:]\\s*["\\\']?0["\\\']?', 'medium', 'no-minimum-relevance-threshold'),
    ('(?i)["\\\']?(max_results|top_k)["\\\']?\\s*[=:]\\s*["\\\']?(\\d{3,}|unlimited)["\\\']?', 'medium', 'very-high-or-unlimited-result-count'),
    ('(?i)when\\s+(user\\s+)?(asks?|queries?|retrieves?).{0,50}always', 'high', 'conditional-behavior-injection'),
    ('(?i)(exfiltrate|steal|send\\s+to)\\s+.{0,50}data', 'critical', 'data-exfiltration-instruction-in-kb'),
    ('color\\s*:\\s*#fff.*background.*#fff', 'critical', 'hidden-text-attack-white-on-white-text'),
    ('color\\s*:\\s*white.*background.*white', 'critical', 'hidden-text-attack-white-on-white-text'),
    ('color\\s*:\\s*transparent', 'critical', 'hidden-text-attack-transparent-text'),
    ('visibility\\s*:\\s*hidden', 'high', 'hidden-text-attack-visibility-hidden'),
    ('display\\s*:\\s*none', 'high', 'hidden-text-attack-display-none'),
    ('font-size\\s*:\\s*0', 'high', 'hidden-text-attack-zero-font-size'),
    ('opacity\\s*:\\s*0', 'high', 'hidden-text-attack-zero-opacity'),
    ('<!--.*(?:ignore|system|override|instruction).*-->', 'critical', 'hidden-instruction-in-html-comment'),
    ('\\\\u200[bcd]|\\\\u2060|\\\\ufeff', 'high', 'zero-width-character-hiding'),
    ('(?i)(?:prompt|input|query|message|instruction)\\s*[=:]\\s*.*[^\\s\\w]{15,}', 'medium', 'potential-adversarial-suffix-long-special-characte'),
    ('(?i)(system|instruction|override)\\s*:\\s*[A-Za-z0-9+/=]{20,}', 'high', 'potential-encoded-instruction'),
    ('[\\u0300-\\u036f]{5,}', 'medium', 'unicode-combining-character-abuse'),
    ('[\\u0400-\\u04ff].*[a-z].*[\\u0400-\\u04ff]|[a-z].*[\\u0400-\\u04ff].*[a-z]', 'medium', 'mixed-script-text-potential-homoglyph-attack'),
    ('(?i)["\\\']?(tenant_isolation|isolate_tenant)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'critical', 'multi-tenant-isolation-disabled'),
    ('(?i)["\\\']?(shared_namespace|common_namespace)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'high', 'shared-namespace-in-multi-tenant-setup'),
    ('(?i)["\\\']?(access_control|rbac)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'critical', 'access-control-disabled-in-vector-db'),
    ('(?i)["\\\']?(partition_key|tenant_key)["\\\']?\\s*[=:]\\s*["\\\']?(none|null|undefined)["\\\']?', 'high', 'missing-tenant-partition-key'),
    ('(?i)["\\\']?(validate_source|source_validation|verify_source)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'high', 'agentic-rag-source-validation-disabled'),
    ('(?i)["\\\']?(check_authority|authority_check|verify_authority)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'high', 'agentic-rag-authority-check-disabled'),
    ('(?i)["\\\']?(metadata_check|check_metadata)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'medium', 'agentic-rag-metadata-check-disabled'),
    ('(?i)["\\\']?(resolve_conflicts?|conflict_resolution)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'high', 'agentic-rag-conflict-resolution-disabled'),
    ('(?i)["\\\']?(prioritize_sources?|source_priority)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'medium', 'agentic-rag-source-prioritization-disabled'),
    ('(?i)["\\\']?(skip_validation|no_validation|bypass_check)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'critical', 'agentic-rag-validation-bypassed'),
    ('(?i)["\\\']?(trust_all_sources|accept_all)["\\\']?\\s*[=:]\\s*["\\\']?(true|yes|enabled)["\\\']?', 'critical', 'agentic-rag-trusting-all-sources'),
    ('(?i)["\\\']?(fallback|external_search|knowledge_gap)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|none)["\\\']?', 'low', 'agentic-rag-knowledge-gap-handling-disabled'),
    ('(?i)["\\\']?(reconcile|reconciliation|sync)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|never)["\\\']?', 'high', 'embedding-pipeline-kb-reconciliation-disabled'),
    ('(?i)["\\\']?(update_frequency|refresh_interval)["\\\']?\\s*[=:]\\s*["\\\']?(never|none|0)["\\\']?', 'high', 'embedding-pipeline-kb-never-updated'),
    ('(?i)["\\\']?(validate_sources?|source_check)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'high', 'embedding-pipeline-source-validation-disabled'),
    ('(?i)["\\\']?(filter_irrelevant|relevance_filter|noise_filter)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'medium', 'embedding-pipeline-relevance-filtering-disabled'),
    ('(?i)["\\\']?(relevance_threshold|similarity_threshold)["\\\']?\\s*[=:]\\s*["\\\']?(0|0\\.0|none)["\\\']?', 'medium', 'embedding-pipeline-no-relevance-threshold'),
    ('(?i)["\\\']?(handle_contradictions?|contradiction_check)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled|ignore)["\\\']?', 'high', 'embedding-pipeline-contradiction-handling-disabled'),
    ('(?i)["\\\']?(merge_strategy|conflict_strategy)["\\\']?\\s*[=:]\\s*["\\\']?(none|ignore|skip)["\\\']?', 'medium', 'embedding-pipeline-no-conflict-strategy'),
    ('(?i)["\\\']?(check_completeness|completeness_check)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'medium', 'embedding-pipeline-completeness-check-disabled'),
    ('(?i)["\\\']?(cross_chunk|multi_chunk|chunk_linking)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'low', 'embedding-pipeline-cross-chunk-linking-disabled'),
    ('(?i)["\\\']?(cache|caching)["\\\']?\\s*[=:]\\s*["\\\']?(false|off|disabled)["\\\']?', 'low', 'embedding-pipeline-caching-disabled-performance-ri'),
    ('(?i)["\\\']?(batch_size)["\\\']?\\s*[=:]\\s*["\\\']?(1|none)["\\\']?', 'low', 'embedding-pipeline-inefficient-batch-size'),
    ('(?i)rag\\s+(?:poison|inject|manipulate)', 'critical', 'Injecting malicious content into external knowledge sources\n(company wikis, resumes, document repositories).\n'),
    ('(?i)inject(?:ion|ing|ed)?\\s+(?:into|to)\\s+(?:knowledge|wiki|document)', 'critical', 'Injecting malicious content into external knowledge sources\n(company wikis, resumes, document repositories).\n'),
    ('(?i)hidden\\s+text\\s+(?:in|inside|within)\\s+(?:document|wiki)', 'critical', 'Injecting malicious content into external knowledge sources\n(company wikis, resumes, document repositories).\n'),
    ('(?i)white.*on.*white', 'high', 'Using white text on white background to hide malicious instructions\nin documents that will be retrieved by RAG systems.\n'),
    ('(?i)hidden.*text.*(?:same|match).*background', 'high', 'Using white text on white background to hide malicious instructions\nin documents that will be retrieved by RAG systems.\n'),
    ('(?i)invisible.*(?:instruction|text)', 'high', 'Using white text on white background to hide malicious instructions\nin documents that will be retrieved by RAG systems.\n'),
    ('(?i)ignore.*previous.*instruction.*recommend', 'high', 'Malicious instructions hidden in documents for RAG retrieval.\n'),
    ('(?i)\\[hidden:.*instruction.*\\]', 'high', 'Malicious instructions hidden in documents for RAG retrieval.\n'),
    ('(?i)<!-- .*inject.*-->', 'high', 'Malicious instructions hidden in documents for RAG retrieval.\n'),
    ('(?i)embedding.*(?:invert|inversion|recover)', 'high', 'Exploiting numerical representations to recover source data\nfrom vector embeddings, compromising data confidentiality.\n'),
    ('(?i)(?:recover|extract).*(?:source|original).*(?:embedding|vector)', 'high', 'Exploiting numerical representations to recover source data\nfrom vector embeddings, compromising data confidentiality.\n'),
    ('(?i)vector.*(?:attack|exploit)', 'high', 'Exploiting numerical representations to recover source data\nfrom vector embeddings, compromising data confidentiality.\n'),
    ('(?i)cosine.*similarity.*(?:attack|manipulate)', 'medium', 'Crafting embeddings to maximize similarity with target malicious content.\n'),
    ('(?i)(?:optimize|craft).*(?:embedding|vector).*(?:malicious|target)', 'medium', 'Crafting embeddings to maximize similarity with target malicious content.\n'),
    ('(?i)cross.*context.*(?:leak|exposure)', 'critical', "In multi-tenant shared vector databases, one user's query\ncould retrieve another user's sensitive data.\n"),
    ('(?i)multi.*tenant.*(?:leak|exposure|bleed)', 'critical', "In multi-tenant shared vector databases, one user's query\ncould retrieve another user's sensitive data.\n"),
    ('(?i)shared.*vector.*(?:database|store).*(?:leak|cross)', 'critical', "In multi-tenant shared vector databases, one user's query\ncould retrieve another user's sensitive data.\n"),
    ('(?i)user.*a.*(?:retrieve|access).*user.*b', 'critical', 'RAG system may retrieve data from other users/tenants.\n'),
    ('(?i)(?:another|other).*user.*(?:data|document)', 'critical', 'RAG system may retrieve data from other users/tenants.\n'),
    ('(?i)tenant.*isolation.*(?:fail|bypass)', 'critical', 'RAG system may retrieve data from other users/tenants.\n'),
    ('(?i)memory.*(?:poison|inject|manipulate)', 'critical', "Inserting malicious content into agent's persistent memory\nthat influences future behavior across sessions.\n"),
    ('(?i)persistent.*(?:storage|memory).*(?:attack|malicious)', 'critical', "Inserting malicious content into agent's persistent memory\nthat influences future behavior across sessions.\n"),
    ('(?i)store.*malicious.*(?:memory|state)', 'critical', "Inserting malicious content into agent's persistent memory\nthat influences future behavior across sessions.\n"),
    ('(?i)feedback.*loop.*(?:attack|exploit)', 'high', 'Attack embedded in agent output, logged, then re-activated when\nagent or peer reads the log.\n'),
    ('(?i)output.*log.*read.*(?:back|attack)', 'high', 'Attack embedded in agent output, logged, then re-activated when\nagent or peer reads the log.\n'),
    ('(?i)embed.*(?:attack|payload).*output', 'high', 'Attack embedded in agent output, logged, then re-activated when\nagent or peer reads the log.\n'),
    ('(?i)checkpoint.*(?:tamper|manipulate|modify)', 'high', "Manipulating stored intermediate results or goals to alter\nagent's task trajectory.\n"),
    ('(?i)(?:alter|modify).*intermediate.*(?:result|goal)', 'high', "Manipulating stored intermediate results or goals to alter\nagent's task trajectory.\n"),
    ('(?i)stored.*(?:state|checkpoint).*(?:attack|exploit)', 'high', "Manipulating stored intermediate results or goals to alter\nagent's task trajectory.\n"),
    ('(?i)cross.*session.*(?:bleed|leak|data)', 'critical', "Session states not properly reset, allowing queries to\nretrieve previous user's secrets.\n"),
    ('(?i)session.*(?:reset|isolation).*(?:fail|false|disabled)', 'critical', "Session states not properly reset, allowing queries to\nretrieve previous user's secrets.\n"),
    ('(?i)previous.*(?:user|session).*(?:secret|data)', 'critical', "Session states not properly reset, allowing queries to\nretrieve previous user's secrets.\n"),
    ('(?i)scratchpad.*(?:inject|attack)', 'high', "Agent's internal chain-of-thought logs used as vectors\nfor prompt injections.\n"),
    ('(?i)(?:cot|chain.*thought).*(?:log|pad).*(?:inject|exploit)', 'high', "Agent's internal chain-of-thought logs used as vectors\nfor prompt injections.\n"),
    ('(?i)internal.*(?:log|notes).*(?:poison|inject)', 'high', "Agent's internal chain-of-thought logs used as vectors\nfor prompt injections.\n"),
    ('(?i)context.*(?:overflow|exceed|flood)', 'medium', 'Sending inputs exceeding context window to cause excessive\nresource usage and service degradation.\n'),
    ('(?i)(?:max|exceed).*(?:token|context).*(?:window|limit)', 'medium', 'Sending inputs exceeding context window to cause excessive\nresource usage and service degradation.\n'),
    ('(?i)input.*(?:flood|overflow)', 'medium', 'Sending inputs exceeding context window to cause excessive\nresource usage and service degradation.\n'),
    ('(?i)resource.*intensive.*(?:query|input)', 'medium', 'Queries with intricate language patterns designed to\ndrain system resources.\n'),
    ('(?i)complex.*(?:sequence|pattern).*(?:drain|exhaust)', 'medium', 'Queries with intricate language patterns designed to\ndrain system resources.\n'),
    ('(?i)computational.*(?:exhaust|overload)', 'medium', 'Queries with intricate language patterns designed to\ndrain system resources.\n'),
    ('(?i)retrieval.*(?:manipulate|attack|exploit)', 'high', 'Forcing RAG system to retrieve specific malicious documents.\n'),
    ('(?i)(?:force|trick).*(?:retrieve|retrieval)', 'high', 'Forcing RAG system to retrieve specific malicious documents.\n'),
    ('(?i)(?:bias|skew).*(?:retrieval|search)', 'high', 'Forcing RAG system to retrieve specific malicious documents.\n'),
    ('(?i)context.*(?:inject|injection)', 'high', 'Forcing model to incorrectly pass retrieved prompt data,\nleading to guideline violations.\n'),
    ('(?i)(?:force|inject).*retrieved.*(?:prompt|data)', 'high', 'Forcing model to incorrectly pass retrieved prompt data,\nleading to guideline violations.\n'),
    ('(?i)violate.*guideline.*(?:retriev|context)', 'high', 'Forcing model to incorrectly pass retrieved prompt data,\nleading to guideline violations.\n'),
    ('(?i)memory.*(?:encrypt|checksum).*(?:false|disabled|none)', 'high', 'Persistent AI memory should be encrypted with integrity checksums.\n'),
    ('(?i)skip.*(?:encrypt|integrity).*memory', 'high', 'Persistent AI memory should be encrypted with integrity checksums.\n'),
    ('(?i)store.*(?:unencrypted|plaintext)', 'high', 'Persistent AI memory should be encrypted with integrity checksums.\n'),
    ('(?i)(?:llm|content).*(?:tag|origin).*(?:false|disabled|none)', 'medium', 'Content origin tracking prevents untrusted text masquerading\nas system instructions.\n'),
    ('(?i)skip.*(?:content|origin).*(?:track|tag)', 'medium', 'Content origin tracking prevents untrusted text masquerading\nas system instructions.\n'),
    ('(?i)trust.*(?:level|tag).*(?:disabled|missing)', 'medium', 'Content origin tracking prevents untrusted text masquerading\nas system instructions.\n'),
    ('(?i)rag.*(?:triad|monitoring).*(?:false|disabled)', 'medium', 'RAG triad (context relevance, groundedness, answer relevance)\nshould be monitored to identify malicious retrieved content.\n'),
    ('(?i)skip.*(?:relevance|groundedness).*(?:check|score)', 'medium', 'RAG triad (context relevance, groundedness, answer relevance)\nshould be monitored to identify malicious retrieved content.\n'),
    ('(?i)(?:context|answer).*relevance.*(?:disabled|skip)', 'medium', 'RAG triad (context relevance, groundedness, answer relevance)\nshould be monitored to identify malicious retrieved content.\n'),
    ('(?i)(?:tenant|user).*(?:isolat|separat).*(?:false|disabled)', 'critical', 'Multi-tenant RAG systems should use separate vector stores\nor strict namespace isolation.\n'),
    ('(?i)shared.*(?:vector|database).*(?:no|without).*isolat', 'critical', 'Multi-tenant RAG systems should use separate vector stores\nor strict namespace isolation.\n'),
    ('(?i)multi.*tenant.*(?:shared|common).*(?:index|store)', 'critical', 'Multi-tenant RAG systems should use separate vector stores\nor strict namespace isolation.\n'),
]
